package policy

import "github.com/securisec/cliam/shared"

var APIGatewayPolicies = []Service{
	{
		Method:        "POST",
		ServiceSuffix: "apikeys",
		JsonData:      map[string]string{},
		Headers: map[string]string{
			shared.CONTENT_TYPE_HEADER: aws_JSON_1_1,
		},
		Permission: "CreateApiKey",
	},
	{
		Method:        "POST",
		ServiceSuffix: "clientcertificates",
		JsonData:      map[string]string{},
		Headers: map[string]string{
			shared.CONTENT_TYPE_HEADER: aws_JSON_1_1,
		},
		Permission: "GenerateClientCertificate",
	},
	{
		Method:        "GET",
		ServiceSuffix: "account",
		Permission:    "GetAccount",
	},
	{
		Method:        "GET",
		ServiceSuffix: "apikeys",
		Permission:    "GetApiKeys",
	},
	{
		Method:        "GET",
		ServiceSuffix: "clientcertificates",
		Permission:    "GetClientCertificates",
	},
	{
		Method:        "GET",
		ServiceSuffix: "domainnames",
		Permission:    "GetDomainNames",
	},
	{
		Method:        "GET",
		ServiceSuffix: "restapis",
		Permission:    "GetRestApis",
	},
	{
		Method:        "GET",
		ServiceSuffix: "sdktypes",
		Permission:    "GetSdkTypes",
	},
	{
		Method:        "GET",
		ServiceSuffix: "usageplans",
		Permission:    "GetUsagePlans",
	},
	{
		Method:        "GET",
		ServiceSuffix: "vpclinks",
		Permission:    "GetVpcLinks",
	},
	{
		Method:        "GET",
		ServiceSuffix: "v2/apis",
		Permission:    "GetApis",
	},
	{
		Method:        "GET",
		ServiceSuffix: "v2/domainnames",
		Permission:    "GetDomainNames",
	},
	{
		Method:        "GET",
		ServiceSuffix: "v2/vpclinks",
		Permission:    "GetVpcLinks",
	},

	// extra policies
	{
		ServiceSuffix:          "/apikeys/{{.api_key}}",
		Permission:             "GetApiKey",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "api_key",
	},
	{
		ServiceSuffix:          "/restapis/{{.rest_api_id}}/authorizers",
		Permission:             "GetAuthorizers",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "rest_api_id",
	},
	{
		ServiceSuffix:          "/domainnames/{{.domain_name}}/basepathmappings",
		Permission:             "GetBasePathMappings",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "domain_name",
	},
	{
		ServiceSuffix:          "/clientcertificates/{{.client_certificate_id}}",
		Permission:             "GetClientCertificate",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "client_certificate_id",
	},
	{
		ServiceSuffix:          "/restapis/{{.rest_api_id}}/deployments",
		Permission:             "GetDeployments",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "rest_api_id",
	},
	{
		ServiceSuffix:          "/restapis/{{.rest_api_id}}/documentation/parts",
		Permission:             "GetDocumentationParts",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "rest_api_id",
	},
	{
		ServiceSuffix:          "/restapis/{{.rest_api_id}}/documentation/versions",
		Permission:             "GetDocumentationVersions",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "rest_api_id",
	},
	{
		ServiceSuffix:          "/domainnames/{{.domain_name}}",
		Permission:             "GetDomainName",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "domain_name",
	},
	{
		ServiceSuffix:          "/restapis/{{.rest_api_id}}/gatewayresponses",
		Permission:             "GetGatewayResponses",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "rest_api_id",
	},
	{
		ServiceSuffix:          "/restapis/{{.rest_api_id}}/models",
		Permission:             "GetModels",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "rest_api_id",
	},
	{
		ServiceSuffix:          "/restapis/{{.rest_api_id}}/requestvalidators",
		Permission:             "GetRequestValidators",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "rest_api_id",
	},
	{
		ServiceSuffix:          "/restapis/{{.rest_api_id}}/resources",
		Permission:             "GetResources",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "rest_api_id",
	},
	{
		ServiceSuffix:          "/restapis/{{.rest_api_id}}",
		Permission:             "GetRestApi",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "rest_api_id",
	},
	{
		ServiceSuffix:          "/sdktypes/{{.id}}",
		Permission:             "GetSdkType",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/restapis/{{.rest_api_id}}/stages",
		Permission:             "GetStages",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "rest_api_id",
	},
	{
		ServiceSuffix:          "/tags/{{.resource_arn}}",
		Permission:             "GetTags",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "resource_arn",
	},
	{
		ServiceSuffix:          "/usageplans/{{.usage_plan_id}}",
		Permission:             "GetUsagePlan",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "usage_plan_id",
	},
	{
		ServiceSuffix:          "/usageplans/{{.usage_plan_id}}/keys",
		Permission:             "GetUsagePlanKeys",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "usage_plan_id",
	},
	{
		ServiceSuffix:          "/vpclinks/{{.vpc_link_id}}",
		Permission:             "GetVpcLink",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "vpc_link_id",
	},
	{
		ServiceSuffix:          "/v2/apis/{{.api_id}}",
		Permission:             "GetApi",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "api_id",
	},
	{
		ServiceSuffix:          "/v2/domainnames/{{.domain_name}}/apimappings",
		Permission:             "GetApiMappings",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "domain_name",
	},
	{
		ServiceSuffix:          "/v2/apis/{{.api_id}}/authorizers",
		Permission:             "GetAuthorizers",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "api_id",
	},
	{
		ServiceSuffix:          "/v2/apis/{{.api_id}}/deployments",
		Permission:             "GetDeployments",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "api_id",
	},
	{
		ServiceSuffix:          "/v2/domainnames/{{.domain_name}}",
		Permission:             "GetDomainName",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "domain_name",
	},
	{
		ServiceSuffix:          "/v2/apis/{{.api_id}}/integrations",
		Permission:             "GetIntegrations",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "api_id",
	},
	{
		ServiceSuffix:          "/v2/apis/{{.api_id}}/models",
		Permission:             "GetModels",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "api_id",
	},
	{
		ServiceSuffix:          "/v2/apis/{{.api_id}}/routes",
		Permission:             "GetRoutes",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "api_id",
	},
	{
		ServiceSuffix:          "/v2/apis/{{.api_id}}/stages",
		Permission:             "GetStages",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "api_id",
	},
	{
		ServiceSuffix:          "/v2/tags/{{.resource_arn}}",
		Permission:             "GetTags",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "resource_arn",
	},
	{
		ServiceSuffix:          "/v2/vpclinks/{{.vpc_link_id}}",
		Permission:             "GetVpcLink",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "vpc_link_id",
	},
}
