package policy

var CloudfrontPolicies = []Service{
	{
		IgnoreRegion:  true,
		ServiceSuffix: "2018-11-05/distribution",
		Permission:    "ListDistributions",
	},
	{
		IgnoreRegion:  true,
		ServiceSuffix: "2020-05-31/cache-policy",
		Permission:    "ListCachePolicies",
	},
	{
		IgnoreRegion:  true,
		ServiceSuffix: "2020-05-31/function",
		Permission:    "ListFunctions",
	},
	{
		IgnoreRegion:  true,
		ServiceSuffix: "2020-05-31/key-group",
		Permission:    "ListKeyGroups",
	},
	{
		IgnoreRegion:  true,
		ServiceSuffix: "2020-05-31/origin-request-policy",
		Permission:    "ListOriginRequestPolicies",
	},
	{
		IgnoreRegion:  true,
		ServiceSuffix: "2020-05-31/realtime-log-config",
		Permission:    "ListRealtimeLogConfigs",
	},
	{
		IgnoreRegion:  true,
		ServiceSuffix: "2020-05-31/response-headers-policy",
		Permission:    "ListResponseHeadersPolicies",
	},
	{
		IgnoreRegion:  true,
		ServiceSuffix: "2020-05-31/origin-access-identity/cloudfront",
		Permission:    "ListCloudFrontOriginAccessIdentities",
	},
	{
		IgnoreRegion:  true,
		ServiceSuffix: "2020-05-31/field-level-encryption",
		Permission:    "ListFieldLevelEncryptionConfigs",
	},
	{
		IgnoreRegion:  true,
		ServiceSuffix: "2020-05-31/field-level-encryption-profile",
		Permission:    "ListFieldLevelEncryptionProfiles",
	},
	{
		IgnoreRegion:  true,
		ServiceSuffix: "2020-05-31/streaming-distribution",
		Permission:    "ListStreamingDistributions",
	},

	// extra
	{
		ServiceSuffix:          "/2020-05-31/function/{{.name}}/describe",
		Permission:             "DescribeFunction",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "name",
	},
	{
		ServiceSuffix:          "/2020-05-31/cache-policy/{{.id}}",
		Permission:             "GetCachePolicy",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/cache-policy/{{.id}}/config",
		Permission:             "GetCachePolicyConfig",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/origin-access-identity/cloudfront/{{.id}}",
		Permission:             "GetCloudFrontOriginAccessIdentity",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/origin-access-identity/cloudfront/{{.id}}/config",
		Permission:             "GetCloudFrontOriginAccessIdentityConfig",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/distribution/{{.id}}",
		Permission:             "GetDistribution",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/distribution/{{.id}}/config",
		Permission:             "GetDistributionConfig",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/field-level-encryption/{{.id}}",
		Permission:             "GetFieldLevelEncryption",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/field-level-encryption/{{.id}}/config",
		Permission:             "GetFieldLevelEncryptionConfig",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/field-level-encryption-profile/{{.id}}",
		Permission:             "GetFieldLevelEncryptionProfile",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/field-level-encryption-profile/{{.id}}/config",
		Permission:             "GetFieldLevelEncryptionProfileConfig",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/function/{{.name}}",
		Permission:             "GetFunction",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "name",
	},
	{
		ServiceSuffix:          "/2020-05-31/key-group/{{.id}}",
		Permission:             "GetKeyGroup",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/key-group/{{.id}}/config",
		Permission:             "GetKeyGroupConfig",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/distributions/{{.distribution_id}}/monitoring-subscription",
		Permission:             "GetMonitoringSubscription",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "distribution_id",
	},
	{
		ServiceSuffix:          "/2020-05-31/origin-request-policy/{{.id}}",
		Permission:             "GetOriginRequestPolicy",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/origin-request-policy/{{.id}}/config",
		Permission:             "GetOriginRequestPolicyConfig",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/public-key/{{.id}}",
		Permission:             "GetPublicKey",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/public-key/{{.id}}/config",
		Permission:             "GetPublicKeyConfig",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/response-headers-policy/{{.id}}",
		Permission:             "GetResponseHeadersPolicy",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/response-headers-policy/{{.id}}/config",
		Permission:             "GetResponseHeadersPolicyConfig",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/streaming-distribution/{{.id}}",
		Permission:             "GetStreamingDistribution",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/streaming-distribution/{{.id}}/config",
		Permission:             "GetStreamingDistributionConfig",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "id",
	},
	{
		ServiceSuffix:          "/2020-05-31/distributionsByCachePolicyId/{{.cache_policy_id}}",
		Permission:             "ListDistributionsByCachePolicyId",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "cache_policy_id",
	},
	{
		ServiceSuffix:          "/2020-05-31/distributionsByKeyGroupId/{{.key_group_id}}",
		Permission:             "ListDistributionsByKeyGroup",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "key_group_id",
	},
	{
		ServiceSuffix:          "/2020-05-31/distributionsByOriginRequestPolicyId/{{.origin_request_policy_id}}",
		Permission:             "ListDistributionsByOriginRequestPolicyId",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "origin_request_policy_id",
	},
	{
		ServiceSuffix:          "/2020-05-31/distributionsByResponseHeadersPolicyId/{{.response_headers_policy_id}}",
		Permission:             "ListDistributionsByResponseHeadersPolicyId",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "response_headers_policy_id",
	},
	{
		ServiceSuffix:          "/2020-05-31/distributionsByWebACLId/{{.web_a_c_l_id}}",
		Permission:             "ListDistributionsByWebACLId",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "web_a_c_l_id",
	},
	{
		ServiceSuffix:          "/2020-05-31/distribution/{{.distribution_id}}/invalidation",
		Permission:             "ListInvalidations",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "distribution_id",
	},
	{
		ServiceSuffix:          "/2020-05-31/tagging",
		Permission:             "ListTagsForResource",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "resource",
	},
}
