package policy

import "github.com/securisec/cliam/shared"

var GreengrassPolicies = []Service{
	{
		Method:        "POST",
		ServiceSuffix: "greengrass/definition/connectors",
		JsonData:      map[string]string{},
		Headers: map[string]string{
			shared.CONTENT_TYPE_HEADER: aws_JSON_1_1,
		},
		Permission: "CreateConnectorDefinition",
	},
	{
		Method:        "POST",
		ServiceSuffix: "greengrass/definition/cores",
		JsonData:      map[string]string{},
		Headers: map[string]string{
			shared.CONTENT_TYPE_HEADER: aws_JSON_1_1,
		},
		Permission: "CreateCoreDefinition",
	},
	{
		Method:        "POST",
		ServiceSuffix: "greengrass/definition/devices",
		JsonData:      map[string]string{},
		Headers: map[string]string{
			shared.CONTENT_TYPE_HEADER: aws_JSON_1_1,
		},
		Permission: "CreateDeviceDefinition",
	},
	{
		Method:        "POST",
		ServiceSuffix: "greengrass/definition/functions",
		JsonData:      map[string]string{},
		Headers: map[string]string{
			shared.CONTENT_TYPE_HEADER: aws_JSON_1_1,
		},
		Permission: "CreateFunctionDefinition",
	},
	{
		Method:        "POST",
		ServiceSuffix: "greengrass/definition/loggers",
		JsonData:      map[string]string{},
		Headers: map[string]string{
			shared.CONTENT_TYPE_HEADER: aws_JSON_1_1,
		},
		Permission: "CreateLoggerDefinition",
	},
	{
		Method:        "POST",
		ServiceSuffix: "greengrass/definition/resources",
		JsonData:      map[string]string{},
		Headers: map[string]string{
			shared.CONTENT_TYPE_HEADER: aws_JSON_1_1,
		},
		Permission: "CreateResourceDefinition",
	},
	{
		Method:        "POST",
		ServiceSuffix: "greengrass/definition/subscriptions",
		JsonData:      map[string]string{},
		Headers: map[string]string{
			shared.CONTENT_TYPE_HEADER: aws_JSON_1_1,
		},
		Permission: "CreateSubscriptionDefinition",
	},
	{
		Method:        "GET",
		ServiceSuffix: "greengrass/servicerole",
		Permission:    "GetServiceRoleForAccount",
	},
	{
		Method:        "GET",
		ServiceSuffix: "greengrass/bulk/deployments",
		Permission:    "ListBulkDeployments",
	},
	{
		Method:        "GET",
		ServiceSuffix: "greengrass/definition/connectors",
		Permission:    "ListConnectorDefinitions",
	},
	{
		Method:        "GET",
		ServiceSuffix: "greengrass/definition/cores",
		Permission:    "ListCoreDefinitions",
	},
	{
		Method:        "GET",
		ServiceSuffix: "greengrass/definition/devices",
		Permission:    "ListDeviceDefinitions",
	},
	{
		Method:        "GET",
		ServiceSuffix: "greengrass/definition/functions",
		Permission:    "ListFunctionDefinitions",
	},
	{
		Method:        "GET",
		ServiceSuffix: "greengrass/groups",
		Permission:    "ListGroups",
	},
	{
		Method:        "GET",
		ServiceSuffix: "greengrass/definition/loggers",
		Permission:    "ListLoggerDefinitions",
	},
	{
		Method:        "GET",
		ServiceSuffix: "greengrass/definition/resources",
		Permission:    "ListResourceDefinitions",
	},
	{
		Method:        "GET",
		ServiceSuffix: "greengrass/definition/subscriptions",
		Permission:    "ListSubscriptionDefinitions",
	},

	// extra
	{
		ServiceSuffix:          "/greengrass/groups/{{.group_id}}/role",
		Permission:             "GetAssociatedRole",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "group_id",
	},
	{
		ServiceSuffix:          "/greengrass/bulk/deployments/{{.bulk_deployment_id}}/status",
		Permission:             "GetBulkDeploymentStatus",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bulk_deployment_id",
	},
	{
		ServiceSuffix:          "/greengrass/things/{{.thing_name}}/connectivityInfo",
		Permission:             "GetConnectivityInfo",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "thing_name",
	},
	{
		ServiceSuffix:          "/greengrass/definition/connectors/{{.connector_definition_id}}",
		Permission:             "GetConnectorDefinition",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "connector_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/cores/{{.core_definition_id}}",
		Permission:             "GetCoreDefinition",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "core_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/devices/{{.device_definition_id}}",
		Permission:             "GetDeviceDefinition",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "device_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/functions/{{.function_definition_id}}",
		Permission:             "GetFunctionDefinition",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "function_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/groups/{{.group_id}}",
		Permission:             "GetGroup",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "group_id",
	},
	{
		ServiceSuffix:          "/greengrass/groups/{{.group_id}}/certificateauthorities/configuration/expiry",
		Permission:             "GetGroupCertificateConfiguration",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "group_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/loggers/{{.logger_definition_id}}",
		Permission:             "GetLoggerDefinition",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "logger_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/resources/{{.resource_definition_id}}",
		Permission:             "GetResourceDefinition",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "resource_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/subscriptions/{{.subscription_definition_id}}",
		Permission:             "GetSubscriptionDefinition",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "subscription_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/things/{{.thing_name}}/runtimeconfig",
		Permission:             "GetThingRuntimeConfiguration",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "thing_name",
	},
	{
		ServiceSuffix:          "/greengrass/bulk/deployments/{{.bulk_deployment_id}}/detailed-reports",
		Permission:             "ListBulkDeploymentDetailedReports",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bulk_deployment_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/connectors/{{.connector_definition_id}}/versions",
		Permission:             "ListConnectorDefinitionVersions",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "connector_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/cores/{{.core_definition_id}}/versions",
		Permission:             "ListCoreDefinitionVersions",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "core_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/groups/{{.group_id}}/deployments",
		Permission:             "ListDeployments",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "group_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/devices/{{.device_definition_id}}/versions",
		Permission:             "ListDeviceDefinitionVersions",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "device_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/functions/{{.function_definition_id}}/versions",
		Permission:             "ListFunctionDefinitionVersions",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "function_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/groups/{{.group_id}}/certificateauthorities",
		Permission:             "ListGroupCertificateAuthorities",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "group_id",
	},
	{
		ServiceSuffix:          "/greengrass/groups/{{.group_id}}/versions",
		Permission:             "ListGroupVersions",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "group_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/loggers/{{.logger_definition_id}}/versions",
		Permission:             "ListLoggerDefinitionVersions",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "logger_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/resources/{{.resource_definition_id}}/versions",
		Permission:             "ListResourceDefinitionVersions",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "resource_definition_id",
	},
	{
		ServiceSuffix:          "/greengrass/definition/subscriptions/{{.subscription_definition_id}}/versions",
		Permission:             "ListSubscriptionDefinitionVersions",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "subscription_definition_id",
	},
	{
		ServiceSuffix:          "/tags/{{.resource_arn}}",
		Permission:             "ListTagsForResource",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "resource_arn",
	},
}
