package policy

var RDSPolicies = []Service{
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBEngineVersions&Version=2014-10-31",
		Permission:    "DescribeDBEngineVersions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBInstances&Version=2014-10-31",
		Permission:    "DescribeDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBParameterGroups&Version=2014-10-31",
		Permission:    "DescribeDBParameterGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSecurityGroups&Version=2014-10-31",
		Permission:    "DescribeDBSecurityGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSnapshots&Version=2014-10-31",
		Permission:    "DescribeDBSnapshots",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSubnetGroups&Version=2014-10-31",
		Permission:    "DescribeDBSubnetGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventCategories&Version=2014-10-31",
		Permission:    "DescribeEventCategories",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventSubscriptions&Version=2014-10-31",
		Permission:    "DescribeEventSubscriptions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeOptionGroups&Version=2014-10-31",
		Permission:    "DescribeOptionGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeReservedDBInstances&Version=2014-10-31",
		Permission:    "DescribeReservedDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeReservedDBInstancesOfferings&Version=2014-10-31",
		Permission:    "DescribeReservedDBInstancesOfferings",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBEngineVersions&Version=2014-10-31",
		Permission:    "DescribeDBEngineVersions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBInstances&Version=2014-10-31",
		Permission:    "DescribeDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBParameterGroups&Version=2014-10-31",
		Permission:    "DescribeDBParameterGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSecurityGroups&Version=2014-10-31",
		Permission:    "DescribeDBSecurityGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSnapshots&Version=2014-10-31",
		Permission:    "DescribeDBSnapshots",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSubnetGroups&Version=2014-10-31",
		Permission:    "DescribeDBSubnetGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventCategories&Version=2014-10-31",
		Permission:    "DescribeEventCategories",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventSubscriptions&Version=2014-10-31",
		Permission:    "DescribeEventSubscriptions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeOptionGroups&Version=2014-10-31",
		Permission:    "DescribeOptionGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeReservedDBInstances&Version=2014-10-31",
		Permission:    "DescribeReservedDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeReservedDBInstancesOfferings&Version=2014-10-31",
		Permission:    "DescribeReservedDBInstancesOfferings",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBEngineVersions&Version=2014-10-31",
		Permission:    "DescribeDBEngineVersions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBInstances&Version=2014-10-31",
		Permission:    "DescribeDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBParameterGroups&Version=2014-10-31",
		Permission:    "DescribeDBParameterGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSecurityGroups&Version=2014-10-31",
		Permission:    "DescribeDBSecurityGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSnapshots&Version=2014-10-31",
		Permission:    "DescribeDBSnapshots",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSubnetGroups&Version=2014-10-31",
		Permission:    "DescribeDBSubnetGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventCategories&Version=2014-10-31",
		Permission:    "DescribeEventCategories",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventSubscriptions&Version=2014-10-31",
		Permission:    "DescribeEventSubscriptions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeOptionGroups&Version=2014-10-31",
		Permission:    "DescribeOptionGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeReservedDBInstances&Version=2014-10-31",
		Permission:    "DescribeReservedDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeReservedDBInstancesOfferings&Version=2014-10-31",
		Permission:    "DescribeReservedDBInstancesOfferings",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBEngineVersions&Version=2014-10-31",
		Permission:    "DescribeDBEngineVersions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBInstances&Version=2014-10-31",
		Permission:    "DescribeDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBParameterGroups&Version=2014-10-31",
		Permission:    "DescribeDBParameterGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSecurityGroups&Version=2014-10-31",
		Permission:    "DescribeDBSecurityGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSnapshots&Version=2014-10-31",
		Permission:    "DescribeDBSnapshots",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSubnetGroups&Version=2014-10-31",
		Permission:    "DescribeDBSubnetGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventCategories&Version=2014-10-31",
		Permission:    "DescribeEventCategories",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventSubscriptions&Version=2014-10-31",
		Permission:    "DescribeEventSubscriptions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeOptionGroups&Version=2014-10-31",
		Permission:    "DescribeOptionGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeReservedDBInstances&Version=2014-10-31",
		Permission:    "DescribeReservedDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeReservedDBInstancesOfferings&Version=2014-10-31",
		Permission:    "DescribeReservedDBInstancesOfferings",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeAccountAttributes&Version=2014-10-31",
		Permission:    "DescribeAccountAttributes",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeCertificates&Version=2014-10-31",
		Permission:    "DescribeCertificates",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeCustomAvailabilityZones&Version=2014-10-31",
		Permission:    "DescribeCustomAvailabilityZones",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBClusterEndpoints&Version=2014-10-31",
		Permission:    "DescribeDBClusterEndpoints",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBClusterParameterGroups&Version=2014-10-31",
		Permission:    "DescribeDBClusterParameterGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBClusterSnapshots&Version=2014-10-31",
		Permission:    "DescribeDBClusterSnapshots",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBClusters&Version=2014-10-31",
		Permission:    "DescribeDBClusters",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBEngineVersions&Version=2014-10-31",
		Permission:    "DescribeDBEngineVersions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBInstanceAutomatedBackups&Version=2014-10-31",
		Permission:    "DescribeDBInstanceAutomatedBackups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBInstances&Version=2014-10-31",
		Permission:    "DescribeDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBParameterGroups&Version=2014-10-31",
		Permission:    "DescribeDBParameterGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBProxies&Version=2014-10-31",
		Permission:    "DescribeDBProxies",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBProxyEndpoints&Version=2014-10-31",
		Permission:    "DescribeDBProxyEndpoints",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSecurityGroups&Version=2014-10-31",
		Permission:    "DescribeDBSecurityGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSnapshots&Version=2014-10-31",
		Permission:    "DescribeDBSnapshots",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSubnetGroups&Version=2014-10-31",
		Permission:    "DescribeDBSubnetGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventCategories&Version=2014-10-31",
		Permission:    "DescribeEventCategories",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventSubscriptions&Version=2014-10-31",
		Permission:    "DescribeEventSubscriptions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeExportTasks&Version=2014-10-31",
		Permission:    "DescribeExportTasks",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeGlobalClusters&Version=2014-10-31",
		Permission:    "DescribeGlobalClusters",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeInstallationMedia&Version=2014-10-31",
		Permission:    "DescribeInstallationMedia",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeOptionGroups&Version=2014-10-31",
		Permission:    "DescribeOptionGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribePendingMaintenanceActions&Version=2014-10-31",
		Permission:    "DescribePendingMaintenanceActions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeReservedDBInstances&Version=2014-10-31",
		Permission:    "DescribeReservedDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeReservedDBInstancesOfferings&Version=2014-10-31",
		Permission:    "DescribeReservedDBInstancesOfferings",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeSourceRegions&Version=2014-10-31",
		Permission:    "DescribeSourceRegions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBClusterEndpoints&Version=2014-10-31",
		Permission:    "DescribeDBClusterEndpoints",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBClusterParameterGroups&Version=2014-10-31",
		Permission:    "DescribeDBClusterParameterGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBClusterSnapshots&Version=2014-10-31",
		Permission:    "DescribeDBClusterSnapshots",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBClusters&Version=2014-10-31",
		Permission:    "DescribeDBClusters",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBEngineVersions&Version=2014-10-31",
		Permission:    "DescribeDBEngineVersions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBInstances&Version=2014-10-31",
		Permission:    "DescribeDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBParameterGroups&Version=2014-10-31",
		Permission:    "DescribeDBParameterGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSubnetGroups&Version=2014-10-31",
		Permission:    "DescribeDBSubnetGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventCategories&Version=2014-10-31",
		Permission:    "DescribeEventCategories",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventSubscriptions&Version=2014-10-31",
		Permission:    "DescribeEventSubscriptions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribePendingMaintenanceActions&Version=2014-10-31",
		Permission:    "DescribePendingMaintenanceActions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeCertificates&Version=2014-10-31",
		Permission:    "DescribeCertificates",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBClusterParameterGroups&Version=2014-10-31",
		Permission:    "DescribeDBClusterParameterGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBClusterSnapshots&Version=2014-10-31",
		Permission:    "DescribeDBClusterSnapshots",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBClusters&Version=2014-10-31",
		Permission:    "DescribeDBClusters",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBEngineVersions&Version=2014-10-31",
		Permission:    "DescribeDBEngineVersions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBInstances&Version=2014-10-31",
		Permission:    "DescribeDBInstances",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeDBSubnetGroups&Version=2014-10-31",
		Permission:    "DescribeDBSubnetGroups",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventCategories&Version=2014-10-31",
		Permission:    "DescribeEventCategories",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeEventSubscriptions&Version=2014-10-31",
		Permission:    "DescribeEventSubscriptions",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribeGlobalClusters&Version=2014-10-31",
		Permission:    "DescribeGlobalClusters",
	},
	{
		Method:        "POST",
		JsonData:      `{}`,
		ServiceSuffix: "?Action=DescribePendingMaintenanceActions&Version=2014-10-31",
		Permission:    "DescribePendingMaintenanceActions",
	},
}
