package policy

// S3Policies policy
var S3Policies = map[string]Service{
	"ListBuckets": {
		Method:        "GET",
		ServiceSuffix: "",
		Permission:    "ListBuckets",
		ResponseParser: &ResponseParser{
			ResponseFormat: "xml",
			KeysToExtract: []CommandLineFlagMap{
				{Flag: "bucket", ResponseKey: "Name"},
			},
			ObjectPath: []string{"ListAllMyBucketsResult", "Buckets", "Bucket"},
		},
	},

	// extra
	"GetBucketAccelerateConfiguration": {
		ServiceSuffix:          "/{{.bucket}}?accelerate",
		Permission:             "GetBucketAccelerateConfiguration",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketAcl": {
		ServiceSuffix:          "/{{.bucket}}?acl",
		Permission:             "GetBucketAcl",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketCors": {
		ServiceSuffix:          "/{{.bucket}}?cors",
		Permission:             "GetBucketCors",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketEncryption": {
		ServiceSuffix:          "/{{.bucket}}?encryption",
		Permission:             "GetBucketEncryption",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketLifecycle": {
		ServiceSuffix:          "/{{.bucket}}?lifecycle",
		Permission:             "GetBucketLifecycle",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketLifecycleConfiguration": {
		ServiceSuffix:          "/{{.bucket}}?lifecycle",
		Permission:             "GetBucketLifecycleConfiguration",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketLocation": {
		ServiceSuffix:          "/{{.bucket}}?location",
		Permission:             "GetBucketLocation",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketLogging": {
		ServiceSuffix:          "/{{.bucket}}?logging",
		Permission:             "GetBucketLogging",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketNotification": {
		ServiceSuffix:          "/{{.bucket}}?notification",
		Permission:             "GetBucketNotification",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketNotificationConfiguration": {
		ServiceSuffix:          "/{{.bucket}}?notification",
		Permission:             "GetBucketNotificationConfiguration",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketOwnershipControls": {
		ServiceSuffix:          "/{{.bucket}}?ownershipControls",
		Permission:             "GetBucketOwnershipControls",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketPolicy": {
		ServiceSuffix:          "/{{.bucket}}?policy",
		Permission:             "GetBucketPolicy",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketPolicyStatus": {
		ServiceSuffix:          "/{{.bucket}}?policyStatus",
		Permission:             "GetBucketPolicyStatus",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketReplication": {
		ServiceSuffix:          "/{{.bucket}}?replication",
		Permission:             "GetBucketReplication",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketRequestPayment": {
		ServiceSuffix:          "/{{.bucket}}?requestPayment",
		Permission:             "GetBucketRequestPayment",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketTagging": {
		ServiceSuffix:          "/{{.bucket}}?tagging",
		Permission:             "GetBucketTagging",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketVersioning": {
		ServiceSuffix:          "/{{.bucket}}?versioning",
		Permission:             "GetBucketVersioning",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetBucketWebsite": {
		ServiceSuffix:          "/{{.bucket}}?website",
		Permission:             "GetBucketWebsite",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetObjectLockConfiguration": {
		ServiceSuffix:          "/{{.bucket}}?object-lock",
		Permission:             "GetObjectLockConfiguration",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"GetPublicAccessBlock": {
		ServiceSuffix:          "/{{.bucket}}?publicAccessBlock",
		Permission:             "GetPublicAccessBlock",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"ListBucketAnalyticsConfigurations": {
		ServiceSuffix:          "/{{.bucket}}?analytics",
		Permission:             "ListBucketAnalyticsConfigurations",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"ListBucketIntelligentTieringConfigurations": {
		ServiceSuffix:          "/{{.bucket}}?intelligent-tiering",
		Permission:             "ListBucketIntelligentTieringConfigurations",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"ListBucketInventoryConfigurations": {
		ServiceSuffix:          "/{{.bucket}}?inventory",
		Permission:             "ListBucketInventoryConfigurations",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"ListBucketMetricsConfigurations": {
		ServiceSuffix:          "/{{.bucket}}?metrics",
		Permission:             "ListBucketMetricsConfigurations",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"ListMultipartUploads": {
		ServiceSuffix:          "/{{.bucket}}?uploads",
		Permission:             "ListMultipartUploads",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"ListObjectVersions": {
		ServiceSuffix:          "/{{.bucket}}?versions",
		Permission:             "ListObjectVersions",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"ListObjects": {
		ServiceSuffix:          "/{{.bucket}}",
		Permission:             "ListObjects",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
	"ListObjectsV2": {
		ServiceSuffix:          "/{{.bucket}}?list-type=2",
		Permission:             "ListObjectsV2",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket",
	},
}
