package policy

var S3Policies = []Service{
	{
		ServiceSuffix: "",
		Permission:    "ListBuckets",
	},

	// extra
	{
		ServiceSuffix:          "/{{.bucket_name}}?accelerate",
		Permission:             "GetBucketAccelerateConfiguration",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?acl",
		Permission:             "GetBucketAcl",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?cors",
		Permission:             "GetBucketCors",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?encryption",
		Permission:             "GetBucketEncryption",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?lifecycle",
		Permission:             "GetBucketLifecycle",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?lifecycle",
		Permission:             "GetBucketLifecycleConfiguration",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?location",
		Permission:             "GetBucketLocation",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?logging",
		Permission:             "GetBucketLogging",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?notification",
		Permission:             "GetBucketNotification",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?notification",
		Permission:             "GetBucketNotificationConfiguration",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?ownershipControls",
		Permission:             "GetBucketOwnershipControls",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?policy",
		Permission:             "GetBucketPolicy",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?policyStatus",
		Permission:             "GetBucketPolicyStatus",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?replication",
		Permission:             "GetBucketReplication",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?requestPayment",
		Permission:             "GetBucketRequestPayment",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?tagging",
		Permission:             "GetBucketTagging",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?versioning",
		Permission:             "GetBucketVersioning",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?website",
		Permission:             "GetBucketWebsite",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?object-lock",
		Permission:             "GetObjectLockConfiguration",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?publicAccessBlock",
		Permission:             "GetPublicAccessBlock",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}",
		Permission:             "HeadBucket",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?analytics",
		Permission:             "ListBucketAnalyticsConfigurations",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?intelligent-tiering",
		Permission:             "ListBucketIntelligentTieringConfigurations",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?inventory",
		Permission:             "ListBucketInventoryConfigurations",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?metrics",
		Permission:             "ListBucketMetricsConfigurations",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?uploads",
		Permission:             "ListMultipartUploads",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?versions",
		Permission:             "ListObjectVersions",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}",
		Permission:             "ListObjects",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
	{
		ServiceSuffix:          "/{{.bucket_name}}?list-type=2",
		Permission:             "ListObjectsV2",
		ExtraComponentLocation: "path",
		IsExtra:                true,
		ExtraCommandLineFlag:   "bucket_name",
	},
}
