package policy

const (
	AccessApproval         = "accessapproval"
	accessapprovalRequests = "accessapproval.requests"
	accessapprovalSettings = "accessapproval.settings"

	AndroidManagement            = "androidmanagement"
	androidmanagementEnterprises = "androidmanagement.enterprises"

	AppEngine             = "appengine"
	appengineApplications = "appengine.applications"
	appengineInstances    = "appengine.instances"
	appengineMemcache     = "appengine.memcache"
	appengineOperations   = "appengine.operations"
	appengineRuntimes     = "appengine.runtimes"
	appengineServices     = "appengine.services"
	appengineVersions     = "appengine.versions"

	AutoMl                     = "automl"
	automlAnnotationSpecs      = "automl.annotationSpecs"
	automlAnnotations          = "automl.annotations"
	automlColumnSpecs          = "automl.columnSpecs"
	automlDatasets             = "automl.datasets"
	automlExamples             = "automl.examples"
	automlHumanAnnotationTasks = "automl.humanAnnotationTasks"
	automlLocations            = "automl.locations"
	automlModelEvaluations     = "automl.modelEvaluations"
	automlModels               = "automl.models"
	automlOperations           = "automl.operations"
	automlTableSpecs           = "automl.tableSpecs"

	AutoMlRecommendations                = "automlrecommendations"
	automlrecommendationsApiKeys         = "automlrecommendations.apiKeys"
	automlrecommendationsCatalogItems    = "automlrecommendations.catalogItems"
	automlrecommendationsCatalogs        = "automlrecommendations.catalogs"
	automlrecommendationsEventStores     = "automlrecommendations.eventStores"
	automlrecommendationsEvents          = "automlrecommendations.events"
	automlrecommendationsPlacements      = "automlrecommendations.placements"
	automlrecommendationsRecommendations = "automlrecommendations.recommendations"

	BigQuery             = "bigquery"
	bigqueryConfig       = "bigquery.config"
	bigqueryConnections  = "bigquery.connections"
	bigqueryDatasets     = "bigquery.datasets"
	bigqueryJobs         = "bigquery.jobs"
	bigqueryModels       = "bigquery.models"
	bigqueryReadsessions = "bigquery.readsessions"
	bigqueryRoutines     = "bigquery.routines"
	bigquerySavedqueries = "bigquery.savedqueries"
	bigqueryTransfers    = "bigquery.transfers"

	BigTable            = "bigtable"
	bigtableAppProfiles = "bigtable.appProfiles"
	bigtableClusters    = "bigtable.clusters"
	bigtableInstances   = "bigtable.instances"
	bigtableLocations   = "bigtable.locations"
	bigtableTables      = "bigtable.tables"

	Billing              = "billing"
	billingResourceCosts = "billing.resourceCosts"

	BinaryAuthorization          = "binaryauthorization"
	binaryauthorizationAttestors = "binaryauthorization.attestors"
	binaryauthorizationPolicy    = "binaryauthorization.policy"

	CloudAsset       = "cloudasset"
	cloudassetAssets = "cloudasset.assets"

	CloudBuild       = "cloudbuild"
	cloudbuildBuilds = "cloudbuild.builds"

	CloudConfig        = "cloudconfig"
	cloudconfigConfigs = "cloudconfig.configs"

	Clouddebugger            = "clouddebugger"
	clouddebuggerBreakpoints = "clouddebugger.breakpoints"
	clouddebuggerDebuggees   = "clouddebugger.debuggees"

	CloudFunctions           = "cloudfunctions"
	cloudfunctionsFunctions  = "cloudfunctions.functions"
	cloudfunctionsLocations  = "cloudfunctions.locations"
	cloudfunctionsOperations = "cloudfunctions.operations"

	CloudIOT           = "cloudiot"
	cloudiotDevices    = "cloudiot.devices"
	cloudiotRegistries = "cloudiot.registries"

	CloudIOTToken              = "cloudiottoken"
	cloudiottokenTokensettings = "cloudiottoken.tokensettings"

	CloudJobDiscovery          = "cloudjobdiscovery"
	cloudjobdiscoveryCompanies = "cloudjobdiscovery.companies"
	cloudjobdiscoveryEvents    = "cloudjobdiscovery.events"
	cloudjobdiscoveryJobs      = "cloudjobdiscovery.jobs"
	cloudjobdiscoveryProfiles  = "cloudjobdiscovery.profiles"
	cloudjobdiscoveryTenants   = "cloudjobdiscovery.tenants"
	cloudjobdiscoveryTools     = "cloudjobdiscovery.tools"

	CloudKMS                  = "cloudkms"
	cloudkmsCryptoKeyVersions = "cloudkms.cryptoKeyVersions"
	cloudkmsCryptoKeys        = "cloudkms.cryptoKeys"
	cloudkmsKeyRings          = "cloudkms.keyRings"

	CloudMessaging         = "cloudmessaging"
	cloudmessagingMessages = "cloudmessaging.messages"

	CloudMigration                    = "cloudmigration"
	cloudmigrationVelostrataendpoints = "cloudmigration.velostrataendpoints"

	CloudNotifications           = "cloudnotifications"
	cloudnotificationsActivities = "cloudnotifications.activities"

	CloudPrivateCatalog        = "cloudprivatecatalog"
	cloudprivatecatalogTargets = "cloudprivatecatalog.targets"

	CloudPrivateCatalogProducer        = "cloudprivatecatalogproducer"
	cloudprivatecatalogproducerTargets = "cloudprivatecatalogproducer.targets"

	Cloudprofiler         = "cloudprofiler"
	cloudprofilerProfiles = "cloudprofiler.profiles"

	CloudScheduler          = "cloudscheduler"
	cloudschedulerJobs      = "cloudscheduler.jobs"
	cloudschedulerLocations = "cloudscheduler.locations"

	CloudSecurityScanner            = "cloudsecurityscanner"
	cloudsecurityscannerCrawledurls = "cloudsecurityscanner.crawledurls"
	cloudsecurityscannerResults     = "cloudsecurityscanner.results"
	cloudsecurityscannerScanruns    = "cloudsecurityscanner.scanruns"
	cloudsecurityscannerScans       = "cloudsecurityscanner.scans"

	CloudSQL           = "cloudsql"
	cloudsqlBackupRuns = "cloudsql.backupRuns"
	cloudsqlDatabases  = "cloudsql.databases"
	cloudsqlInstances  = "cloudsql.instances"
	cloudsqlSslCerts   = "cloudsql.sslCerts"
	cloudsqlUsers      = "cloudsql.users"

	CloudTasks          = "cloudtasks"
	cloudtasksLocations = "cloudtasks.locations"
	cloudtasksQueues    = "cloudtasks.queues"
	cloudtasksTasks     = "cloudtasks.tasks"

	CloudTestService                   = "cloudtestservice"
	cloudtestserviceEnvironmentcatalog = "cloudtestservice.environmentcatalog"
	cloudtestserviceMatrices           = "cloudtestservice.matrices"

	CloudToolResults           = "cloudtoolresults"
	cloudtoolresultsExecutions = "cloudtoolresults.executions"
	cloudtoolresultsHistories  = "cloudtoolresults.histories"
	cloudtoolresultsSettings   = "cloudtoolresults.settings"
	cloudtoolresultsSteps      = "cloudtoolresults.steps"

	CloudTrace         = "cloudtrace"
	cloudtraceInsights = "cloudtrace.insights"
	cloudtraceStats    = "cloudtrace.stats"
	cloudtraceTasks    = "cloudtrace.tasks"
	cloudtraceTraces   = "cloudtrace.traces"

	CloudTranslate                        = "cloudtranslate"
	cloudtranslateGeneralModels           = "cloudtranslate.generalModels"
	cloudtranslateGlossaries              = "cloudtranslate.glossaries"
	cloudtranslateLanguageDetectionModels = "cloudtranslate.languageDetectionModels"
	cloudtranslateLocations               = "cloudtranslate.locations"
	cloudtranslateOperations              = "cloudtranslate.operations"

	Composer              = "composer"
	composerEnvironments  = "composer.environments"
	composerImageversions = "composer.imageversions"
	composerOperations    = "composer.operations"

	Compute                        = "compute"
	computeAcceleratorTypes        = "compute.acceleratorTypes"
	computeAddresses               = "compute.addresses"
	computeAutoscalers             = "compute.autoscalers"
	computeBackendBuckets          = "compute.backendBuckets"
	computeBackendServices         = "compute.backendServices"
	computeCommitments             = "compute.commitments"
	computeDiskTypes               = "compute.diskTypes"
	computeDisks                   = "compute.disks"
	computeFirewalls               = "compute.firewalls"
	computeForwardingRules         = "compute.forwardingRules"
	computeGlobalAddresses         = "compute.globalAddresses"
	computeGlobalForwardingRules   = "compute.globalForwardingRules"
	computeGlobalOperations        = "compute.globalOperations"
	computeHealthChecks            = "compute.healthChecks"
	computeHttpHealthChecks        = "compute.httpHealthChecks"
	computeHttpsHealthChecks       = "compute.httpsHealthChecks"
	computeImages                  = "compute.images"
	computeInstanceGroupManagers   = "compute.instanceGroupManagers"
	computeInstanceGroups          = "compute.instanceGroups"
	computeInstanceTemplates       = "compute.instanceTemplates"
	computeInstances               = "compute.instances"
	computeInterconnectAttachments = "compute.interconnectAttachments"
	computeInterconnectLocations   = "compute.interconnectLocations"
	computeInterconnects           = "compute.interconnects"
	computeLicenseCodes            = "compute.licenseCodes"
	computeLicenses                = "compute.licenses"
	computeMachineTypes            = "compute.machineTypes"
	computeMaintenancePolicies     = "compute.maintenancePolicies"
	computeNetworkEndpointGroups   = "compute.networkEndpointGroups"
	computeNetworks                = "compute.networks"
	computeNodeGroups              = "compute.nodeGroups"
	computeNodeTemplates           = "compute.nodeTemplates"
	computeNodeTypes               = "compute.nodeTypes"
	computeProjects                = "compute.projects"
	computeRegionBackendServices   = "compute.regionBackendServices"
	computeRegionOperations        = "compute.regionOperations"
	computeRegions                 = "compute.regions"
	computeReservations            = "compute.reservations"
	computeResourcePolicies        = "compute.resourcePolicies"
	computeRouters                 = "compute.routers"
	computeRoutes                  = "compute.routes"
	computeSecurityPolicies        = "compute.securityPolicies"
	computeSnapshots               = "compute.snapshots"
	computeSslCertificates         = "compute.sslCertificates"
	computeSslPolicies             = "compute.sslPolicies"
	computeSubnetworks             = "compute.subnetworks"
	computeTargetHttpProxies       = "compute.targetHttpProxies"
	computeTargetHttpsProxies      = "compute.targetHttpsProxies"
	computeTargetInstances         = "compute.targetInstances"
	computeTargetPools             = "compute.targetPools"
	computeTargetSslProxies        = "compute.targetSslProxies"
	computeTargetTcpProxies        = "compute.targetTcpProxies"
	computeTargetVpnGateways       = "compute.targetVpnGateways"
	computeUrlMaps                 = "compute.urlMaps"
	computeVpnGateways             = "compute.vpnGateways"
	computeVpnTunnels              = "compute.vpnTunnels"
	computeZoneOperations          = "compute.zoneOperations"
	computeZones                   = "compute.zones"

	Container                           = "container"
	containerApiServices                = "container.apiServices"
	containerBackendConfigs             = "container.backendConfigs"
	containerBindings                   = "container.bindings"
	containerCertificateSigningRequests = "container.certificateSigningRequests"
	containerClusterRoleBindings        = "container.clusterRoleBindings"
	containerClusterRoles               = "container.clusterRoles"
	containerClusters                   = "container.clusters"
	containerComponentStatuses          = "container.componentStatuses"
	containerConfigMaps                 = "container.configMaps"
	containerControllerRevisions        = "container.controllerRevisions"
	containerCronJobs                   = "container.cronJobs"
	containerCustomResourceDefinitions  = "container.customResourceDefinitions"
	containerDaemonSets                 = "container.daemonSets"
	containerDeployments                = "container.deployments"
	containerEndpoints                  = "container.endpoints"
	containerEvents                     = "container.events"
	containerHorizontalPodAutoscalers   = "container.horizontalPodAutoscalers"
	containerIngresses                  = "container.ingresses"
	containerInitializerConfigurations  = "container.initializerConfigurations"
	containerJobs                       = "container.jobs"
	containerLimitRanges                = "container.limitRanges"
	containerLocalSubjectAccessReviews  = "container.localSubjectAccessReviews"
	containerNamespaces                 = "container.namespaces"
	containerNetworkPolicies            = "container.networkPolicies"
	containerNodes                      = "container.nodes"
	containerOperations                 = "container.operations"
	containerPersistentVolumeClaims     = "container.persistentVolumeClaims"
	containerPersistentVolumes          = "container.persistentVolumes"
	containerPetSets                    = "container.petSets"
	containerPodDisruptionBudgets       = "container.podDisruptionBudgets"
	containerPodPresets                 = "container.podPresets"
	containerPodSecurityPolicies        = "container.podSecurityPolicies"
	containerPodTemplates               = "container.podTemplates"
	containerPods                       = "container.pods"
	containerReplicaSets                = "container.replicaSets"
	containerReplicationControllers     = "container.replicationControllers"
	containerResourceQuotas             = "container.resourceQuotas"
	containerRoleBindings               = "container.roleBindings"
	containerRoles                      = "container.roles"
	containerScheduledJobs              = "container.scheduledJobs"
	containerSecrets                    = "container.secrets"
	containerSelfSubjectAccessReviews   = "container.selfSubjectAccessReviews"
	containerServiceAccounts            = "container.serviceAccounts"
	containerServices                   = "container.services"
	containerStatefulSets               = "container.statefulSets"
	containerStorageClasses             = "container.storageClasses"
	containerSubjectAccessReviews       = "container.subjectAccessReviews"
	containerThirdPartyObjects          = "container.thirdPartyObjects"
	containerThirdPartyResources        = "container.thirdPartyResources"
	containerTokenReviews               = "container.tokenReviews"

	DataCatalog             = "datacatalog"
	datacatalogEntries      = "datacatalog.entries"
	datacatalogEntryGroups  = "datacatalog.entryGroups"
	datacatalogTagTemplates = "datacatalog.tagTemplates"

	DataFlowJobs     = "dataflow"
	dataflowJobs     = "dataflow.jobs"
	dataflowMessages = "dataflow.messages"
	dataflowMetrics  = "dataflow.metrics"

	DataFusion           = "datafusion"
	datafusionInstances  = "datafusion.instances"
	datafusionLocations  = "datafusion.locations"
	datafusionOperations = "datafusion.operations"

	DataLabeling                   = "datalabeling"
	datalabelingAnnotateddatasets  = "datalabeling.annotateddatasets"
	datalabelingAnnotationspecsets = "datalabeling.annotationspecsets"
	datalabelingDataitems          = "datalabeling.dataitems"
	datalabelingDatasets           = "datalabeling.datasets"
	datalabelingExamples           = "datalabeling.examples"
	datalabelingInstructions       = "datalabeling.instructions"
	datalabelingOperations         = "datalabeling.operations"

	DataPrep         = "dataprep"
	dataprepProjects = "dataprep.projects"

	DataProc                  = "dataproc"
	dataprocAgents            = "dataproc.agents"
	dataprocClusters          = "dataproc.clusters"
	dataprocJobs              = "dataproc.jobs"
	dataprocOperations        = "dataproc.operations"
	dataprocTasks             = "dataproc.tasks"
	dataprocWorkflowTemplates = "dataproc.workflowTemplates"

	DataStore           = "datastore"
	datastoreDatabases  = "datastore.databases"
	datastoreEntities   = "datastore.entities"
	datastoreIndexes    = "datastore.indexes"
	datastoreLocations  = "datastore.locations"
	datastoreNamespaces = "datastore.namespaces"
	datastoreOperations = "datastore.operations"
	datastoreStatistics = "datastore.statistics"

	DeploymentManager               = "deploymentmanager"
	deploymentmanagerCompositeTypes = "deploymentmanager.compositeTypes"
	deploymentmanagerDeployments    = "deploymentmanager.deployments"
	deploymentmanagerManifests      = "deploymentmanager.manifests"
	deploymentmanagerOperations     = "deploymentmanager.operations"
	deploymentmanagerResources      = "deploymentmanager.resources"
	deploymentmanagerTypeProviders  = "deploymentmanager.typeProviders"
	deploymentmanagerTypes          = "deploymentmanager.types"

	DialogFlow                   = "dialogflow"
	dialogflowAgents             = "dialogflow.agents"
	dialogflowContexts           = "dialogflow.contexts"
	dialogflowEntityTypes        = "dialogflow.entityTypes"
	dialogflowIntents            = "dialogflow.intents"
	dialogflowOperations         = "dialogflow.operations"
	dialogflowSessionEntityTypes = "dialogflow.sessionEntityTypes"
	dialogflowSessions           = "dialogflow.sessions"

	DLP                     = "dlp"
	dlpAnalyzeRiskTemplates = "dlp.analyzeRiskTemplates"
	dlpDeidentifyTemplates  = "dlp.deidentifyTemplates"
	dlpInspectTemplates     = "dlp.inspectTemplates"
	dlpJobTriggers          = "dlp.jobTriggers"
	dlpJobs                 = "dlp.jobs"
	dlpKms                  = "dlp.kms"
	dlpStoredInfoTypes      = "dlp.storedInfoTypes"

	DNS                      = "dns"
	dnsChanges               = "dns.changes"
	dnsDnsKeys               = "dns.dnsKeys"
	dnsManagedZoneOperations = "dns.managedZoneOperations"
	dnsManagedZones          = "dns.managedZones"
	dnsNetworks              = "dns.networks"
	dnsPolicies              = "dns.policies"
	dnsProjects              = "dns.projects"
	dnsResourceRecordSets    = "dns.resourceRecordSets"

	Endpoints        = "endpoints"
	endpointsPortals = "endpoints.portals"

	ErrorReporting              = "errorreporting"
	errorreportingApplications  = "errorreporting.applications"
	errorreportingErrorEvents   = "errorreporting.errorEvents"
	errorreportingGroupMetadata = "errorreporting.groupMetadata"
	errorreportingGroups        = "errorreporting.groups"

	File           = "file"
	fileInstances  = "file.instances"
	fileLocations  = "file.locations"
	fileOperations = "file.operations"
	fileSnapshots  = "file.snapshots"

	Firebase             = "firebase"
	firebaseBillingPlans = "firebase.billingPlans"
	firebaseClients      = "firebase.clients"
	firebaseLinks        = "firebase.links"
	firebaseProjects     = "firebase.projects"

	FirebaseAbt                  = "firebaseabt"
	firebaseabtExperimentresults = "firebaseabt.experimentresults"
	firebaseabtExperiments       = "firebaseabt.experiments"
	firebaseabtProjectmetadata   = "firebaseabt.projectmetadata"

	FirebaseAnalytics          = "firebaseanalytics"
	firebaseanalyticsResources = "firebaseanalytics.resources"

	FirebaseAuth        = "firebaseauth"
	firebaseauthConfigs = "firebaseauth.configs"
	firebaseauthUsers   = "firebaseauth.users"

	FirebaseCrash        = "firebasecrash"
	firebasecrashIssues  = "firebasecrash.issues"
	firebasecrashReports = "firebasecrash.reports"

	FirebaseCrashlytics         = "firebasecrashlytics"
	firebasecrashlyticsConfig   = "firebasecrashlytics.config"
	firebasecrashlyticsData     = "firebasecrashlytics.data"
	firebasecrashlyticsIssues   = "firebasecrashlytics.issues"
	firebasecrashlyticsSessions = "firebasecrashlytics.sessions"

	FirebaseDatabase          = "firebasedatabase"
	firebasedatabaseInstances = "firebasedatabase.instances"

	FirebaseDynamicLinks             = "firebasedynamiclinks"
	firebasedynamiclinksDestinations = "firebasedynamiclinks.destinations"
	firebasedynamiclinksDomains      = "firebasedynamiclinks.domains"
	firebasedynamiclinksLinks        = "firebasedynamiclinks.links"
	firebasedynamiclinksStats        = "firebasedynamiclinks.stats"

	FirebaseExtensions        = "firebaseextensions"
	firebaseextensionsConfigs = "firebaseextensions.configs"

	FirebaseHosting      = "firebasehosting"
	firebasehostingSites = "firebasehosting.sites"

	FirebaseInAppMessaging          = "firebaseinappmessaging"
	firebaseinappmessagingCampaigns = "firebaseinappmessaging.campaigns"

	FirebaseML                = "firebaseml"
	firebasemlCompressionjobs = "firebaseml.compressionjobs"
	firebasemlModels          = "firebaseml.models"
	firebasemlModelversions   = "firebaseml.modelversions"

	FirebaseNotifications         = "firebasenotifications"
	firebasenotificationsMessages = "firebasenotifications.messages"

	FirebasePerformance       = "firebaseperformance"
	firebaseperformanceConfig = "firebaseperformance.config"
	firebaseperformanceData   = "firebaseperformance.data"

	FirebasePredictions            = "firebasepredictions"
	firebasepredictionsPredictions = "firebasepredictions.predictions"

	FirebaseRules         = "firebaserules"
	firebaserulesReleases = "firebaserules.releases"
	firebaserulesRulesets = "firebaserules.rulesets"

	Genomics           = "genomics"
	genomicsDatasets   = "genomics.datasets"
	genomicsOperations = "genomics.operations"

	Healthcare              = "healthcare"
	healthcareDatasets      = "healthcare.datasets"
	healthcareDicomStores   = "healthcare.dicomStores"
	healthcareFhirResources = "healthcare.fhirResources"
	healthcareFhirStores    = "healthcare.fhirStores"
	healthcareHl7V2Messages = "healthcare.hl7V2Messages"
	healthcareHl7V2Stores   = "healthcare.hl7V2Stores"
	healthcareOperations    = "healthcare.operations"

	Iam                   = "iam"
	iamRoles              = "iam.roles"
	iamServiceAccountKeys = "iam.serviceAccountKeys"
	iamServiceAccounts    = "iam.serviceAccounts"

	Iap                   = "iap"
	iapTunnel             = "iap.tunnel"
	iapTunnelInstances    = "iap.tunnelInstances"
	iapTunnelZones        = "iap.tunnelZones"
	iapWeb                = "iap.web"
	iapWebServiceVersions = "iap.webServiceVersions"
	iapWebServices        = "iap.webServices"
	iapWebTypes           = "iap.webTypes"

	Logging                  = "logging"
	loggingExclusions        = "logging.exclusions"
	loggingLogEntries        = "logging.logEntries"
	loggingLogMetrics        = "logging.logMetrics"
	loggingLogServiceIndexes = "logging.logServiceIndexes"
	loggingLogServices       = "logging.logServices"
	loggingLogs              = "logging.logs"
	loggingPrivateLogEntries = "logging.privateLogEntries"
	loggingSinks             = "logging.sinks"
	loggingUsage             = "logging.usage"

	ManagedIdentities           = "managedidentities"
	managedidentitiesDomains    = "managedidentities.domains"
	managedidentitiesLocations  = "managedidentities.locations"
	managedidentitiesOperations = "managedidentities.operations"

	ML           = "ml"
	mlJobs       = "ml.jobs"
	mlLocations  = "ml.locations"
	mlModels     = "ml.models"
	mlOperations = "ml.operations"
	mlProjects   = "ml.projects"
	mlVersions   = "ml.versions"

	Monitoring                               = "monitoring"
	monitoringAlertPolicies                  = "monitoring.alertPolicies"
	monitoringDashboards                     = "monitoring.dashboards"
	monitoringGroups                         = "monitoring.groups"
	monitoringMetricDescriptors              = "monitoring.metricDescriptors"
	monitoringMonitoredResourceDescriptors   = "monitoring.monitoredResourceDescriptors"
	monitoringNotificationChannelDescriptors = "monitoring.notificationChannelDescriptors"
	monitoringNotificationChannels           = "monitoring.notificationChannels"
	monitoringPublicWidgets                  = "monitoring.publicWidgets"
	monitoringTimeSeries                     = "monitoring.timeSeries"
	monitoringUptimeCheckConfigs             = "monitoring.uptimeCheckConfigs"

	OrgPolicy       = "orgpolicy"
	orgpolicyPolicy = "orgpolicy.policy"

	ProximityBeacon            = "proximitybeacon"
	proximitybeaconAttachments = "proximitybeacon.attachments"
	proximitybeaconBeacons     = "proximitybeacon.beacons"
	proximitybeaconNamespaces  = "proximitybeacon.namespaces"

	Pubsub              = "pubsub"
	pubsubSnapshots     = "pubsub.snapshots"
	pubsubSubscriptions = "pubsub.subscriptions"
	pubsubTopics        = "pubsub.topics"

	Redis           = "redis"
	redisInstances  = "redis.instances"
	redisLocations  = "redis.locations"
	redisOperations = "redis.operations"

	RemoteBuildExecution            = "remotebuildexecution"
	remotebuildexecutionActions     = "remotebuildexecution.actions"
	remotebuildexecutionBlobs       = "remotebuildexecution.blobs"
	remotebuildexecutionBotsessions = "remotebuildexecution.botsessions"
	remotebuildexecutionInstances   = "remotebuildexecution.instances"
	remotebuildexecutionLogstreams  = "remotebuildexecution.logstreams"
	remotebuildexecutionWorkerpools = "remotebuildexecution.workerpools"

	ResourceManager         = "resourcemanager"
	resourcemanagerProjects = "resourcemanager.projects"

	Run               = "run"
	runConfigurations = "run.configurations"
	runLocations      = "run.locations"
	runRevisions      = "run.revisions"
	runRoutes         = "run.routes"
	runServices       = "run.services"

	RuntimeConfig           = "runtimeconfig"
	runtimeconfigConfigs    = "runtimeconfig.configs"
	runtimeconfigOperations = "runtimeconfig.operations"
	runtimeconfigVariables  = "runtimeconfig.variables"
	runtimeconfigWaiters    = "runtimeconfig.waiters"

	SecretManager = "secretmanager"
	secretManager = "secretmanager.secrets"

	ServiceBroker                   = "servicebroker"
	servicebrokerBindingoperations  = "servicebroker.bindingoperations"
	servicebrokerBindings           = "servicebroker.bindings"
	servicebrokerCatalogs           = "servicebroker.catalogs"
	servicebrokerInstanceoperations = "servicebroker.instanceoperations"
	servicebrokerInstances          = "servicebroker.instances"

	ServiceConsumerManagement          = "serviceconsumermanagement"
	serviceconsumermanagementConsumers = "serviceconsumermanagement.consumers"
	serviceconsumermanagementQuota     = "serviceconsumermanagement.quota"
	serviceconsumermanagementTenancyu  = "serviceconsumermanagement.tenancyu"

	ServiceManagement         = "servicemanagement"
	servicemanagementServices = "servicemanagement.services"

	ServiceNetworking           = "servicenetworking"
	servicenetworkingOperations = "servicenetworking.operations"
	servicenetworkingServices   = "servicenetworking.services"

	ServiceUsage           = "serviceusage"
	serviceusageApiKeys    = "serviceusage.apiKeys"
	serviceusageOperations = "serviceusage.operations"
	serviceusageQuotas     = "serviceusage.quotas"
	serviceusageServices   = "serviceusage.services"

	Source      = "source"
	sourceRepos = "source.repos"

	Spanner                   = "spanner"
	spannerDatabaseOperations = "spanner.databaseOperations"
	spannerDatabases          = "spanner.databases"
	spannerInstanceConfigs    = "spanner.instanceConfigs"
	spannerInstanceOperations = "spanner.instanceOperations"
	spannerInstances          = "spanner.instances"
	spannerSessions           = "spanner.sessions"

	StackDriver                 = "stackdriver"
	stackdriverProjects         = "stackdriver.projects"
	stackdriverResourceMetadata = "stackdriver.resourceMetadata"

	Storage         = "storage"
	storageBuckets  = "storage.buckets"
	storageObjects  = "storage.objects"
	storageHmacKeys = "storage.hmacKeys"

	StorageTransfer           = "storagetransfer"
	storagetransferJobs       = "storagetransfer.jobs"
	storagetransferOperations = "storagetransfer.operations"
	storagetransferProjects   = "storagetransfer.projects"

	SubscribeTithGoogleDeveloper      = "subscribewithgoogledeveloper"
	subscribewithgoogledeveloperTools = "subscribewithgoogledeveloper.tools"

	ThreatDetection                 = "threatdetection"
	threatdetectionDetectorSettings = "threatdetection.detectorSettings"

	Tpu                   = "tpu"
	tpuAcceleratortypes   = "tpu.acceleratortypes"
	tpuLocations          = "tpu.locations"
	tpuNodes              = "tpu.nodes"
	tpuOperations         = "tpu.operations"
	tpuTensorflowversions = "tpu.tensorflowversions"

	VpcAccess           = "vpcaccess"
	vpcaccessConnectors = "vpcaccess.connectors"
	vpcaccessLocations  = "vpcaccess.locations"
	vpcaccessOperations = "vpcaccess.operations"
)
