package policy

type Service struct {
	Actions []string
	Method  string
}

var Resources = map[string]Service{
	AccessapprovalRequests:                   {Method: AccessapprovalRequests, Actions: []string{"approve", "dismiss", "get", "list"}},
	AccessapprovalSettings:                   {Method: AccessapprovalSettings, Actions: []string{"get", "update"}},
	AndroidmanagementEnterprises:             {Method: AndroidmanagementEnterprises, Actions: []string{"manage"}},
	AppengineApplications:                    {Method: AppengineApplications, Actions: []string{"create", "get", "update"}},
	AppengineInstances:                       {Method: AppengineInstances, Actions: []string{"delete", "get", "list"}},
	AppengineMemcache:                        {Method: AppengineMemcache, Actions: []string{"addKey", "flush", "get", "getKey", "list", "update"}},
	AppengineOperations:                      {Method: AppengineOperations, Actions: []string{"get", "list"}},
	AppengineRuntimes:                        {Method: AppengineRuntimes, Actions: []string{"actAsAdmin"}},
	AppengineServices:                        {Method: AppengineServices, Actions: []string{"delete", "get", "list", "update"}},
	AppengineVersions:                        {Method: AppengineVersions, Actions: []string{"create", "delete", "get", "getFileContents", "list", "update"}},
	AutomlAnnotationSpecs:                    {Method: AutomlAnnotationSpecs, Actions: []string{"create", "delete", "get", "list", "update"}},
	AutomlAnnotations:                        {Method: AutomlAnnotations, Actions: []string{"approve", "create", "list", "manipulate", "reject"}},
	AutomlColumnSpecs:                        {Method: AutomlColumnSpecs, Actions: []string{"get", "list", "update"}},
	AutomlDatasets:                           {Method: AutomlDatasets, Actions: []string{"create", "delete", "export", "get", "getIamPolicy", "import", "list", "setIamPolicy", "update"}},
	AutomlExamples:                           {Method: AutomlExamples, Actions: []string{"delete", "get", "list"}},
	AutomlHumanAnnotationTasks:               {Method: AutomlHumanAnnotationTasks, Actions: []string{"create", "delete", "get", "list"}},
	AutomlLocations:                          {Method: AutomlLocations, Actions: []string{"get", "getIamPolicy", "list", "setIamPolicy"}},
	AutomlModelEvaluations:                   {Method: AutomlModelEvaluations, Actions: []string{"create", "get", "list"}},
	AutomlModels:                             {Method: AutomlModels, Actions: []string{"create", "delete", "deploy", "export", "get", "getIamPolicy", "list", "predict", "setIamPolicy", "undeploy"}},
	AutomlOperations:                         {Method: AutomlOperations, Actions: []string{"cancel", "delete", "get", "list"}},
	AutomlTableSpecs:                         {Method: AutomlTableSpecs, Actions: []string{"get", "list", "update"}},
	AutomlrecommendationsApiKeys:             {Method: AutomlrecommendationsApiKeys, Actions: []string{"create", "delete", "list"}},
	AutomlrecommendationsCatalogItems:        {Method: AutomlrecommendationsCatalogItems, Actions: []string{"create", "delete", "get", "list", "update"}},
	AutomlrecommendationsCatalogs:            {Method: AutomlrecommendationsCatalogs, Actions: []string{"getStats", "list"}},
	AutomlrecommendationsEventStores:         {Method: AutomlrecommendationsEventStores, Actions: []string{"getStats"}},
	AutomlrecommendationsEvents:              {Method: AutomlrecommendationsEvents, Actions: []string{"create", "list", "purge"}},
	AutomlrecommendationsPlacements:          {Method: AutomlrecommendationsPlacements, Actions: []string{"getStats", "list"}},
	AutomlrecommendationsRecommendations:     {Method: AutomlrecommendationsRecommendations, Actions: []string{"list"}},
	BigqueryConfig:                           {Method: BigqueryConfig, Actions: []string{"get", "update"}},
	BigqueryConnections:                      {Method: BigqueryConnections, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update", "use"}},
	BigqueryDatasets:                         {Method: BigqueryDatasets, Actions: []string{"create", "delete", "get", "getIamPolicy", "setIamPolicy", "update", "updateTag"}},
	BigqueryJobs:                             {Method: BigqueryJobs, Actions: []string{"create", "get", "list", "listAll", "update"}},
	BigqueryModels:                           {Method: BigqueryModels, Actions: []string{"create", "delete", "getData", "getMetadata", "list", "updateData", "updateMetadata", "updateTag"}},
	BigqueryReadsessions:                     {Method: BigqueryReadsessions, Actions: []string{"create"}},
	BigqueryRoutines:                         {Method: BigqueryRoutines, Actions: []string{"create", "delete", "get", "list", "update"}},
	BigquerySavedqueries:                     {Method: BigquerySavedqueries, Actions: []string{"create", "delete", "get", "list", "update"}},
	BigqueryTransfers:                        {Method: BigqueryTransfers, Actions: []string{"get", "update"}},
	BigtableAppProfiles:                      {Method: BigtableAppProfiles, Actions: []string{"create", "delete", "get", "list", "update"}},
	BigtableClusters:                         {Method: BigtableClusters, Actions: []string{"create", "delete", "get", "list", "update"}},
	BigtableInstances:                        {Method: BigtableInstances, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	BigtableLocations:                        {Method: BigtableLocations, Actions: []string{"list"}},
	BigtableTables:                           {Method: BigtableTables, Actions: []string{"checkConsistency", "create", "delete", "generateConsistencyToken", "get", "list", "mutateRows", "readRows", "sampleRowKeys", "update"}},
	BillingResourceCosts:                     {Method: BillingResourceCosts, Actions: []string{"get"}},
	BinaryauthorizationAttestors:             {Method: BinaryauthorizationAttestors, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update", "verifyImageAttested"}},
	BinaryauthorizationPolicy:                {Method: BinaryauthorizationPolicy, Actions: []string{"get", "getIamPolicy", "setIamPolicy", "update"}},
	CloudassetAssets:                         {Method: CloudassetAssets, Actions: []string{"exportIamPolicy", "exportResource"}},
	CloudbuildBuilds:                         {Method: CloudbuildBuilds, Actions: []string{"create", "get", "list", "update"}},
	CloudconfigConfigs:                       {Method: CloudconfigConfigs, Actions: []string{"get", "update"}},
	ClouddebuggerBreakpoints:                 {Method: ClouddebuggerBreakpoints, Actions: []string{"create", "delete", "get", "list", "listActive", "update"}},
	ClouddebuggerDebuggees:                   {Method: ClouddebuggerDebuggees, Actions: []string{"create", "list"}},
	CloudfunctionsFunctions:                  {Method: CloudfunctionsFunctions, Actions: []string{"call", "create", "delete", "get", "getIamPolicy", "invoke", "list", "setIamPolicy", "sourceCodeGet", "sourceCodeSet", "update"}},
	CloudfunctionsLocations:                  {Method: CloudfunctionsLocations, Actions: []string{"list"}},
	CloudfunctionsOperations:                 {Method: CloudfunctionsOperations, Actions: []string{"get", "list"}},
	CloudiotDevices:                          {Method: CloudiotDevices, Actions: []string{"bindGateway", "create", "delete", "get", "list", "sendCommand", "unbindGateway", "update", "updateConfig"}},
	CloudiotRegistries:                       {Method: CloudiotRegistries, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	CloudiottokenTokensettings:               {Method: CloudiottokenTokensettings, Actions: []string{"get", "update"}},
	CloudjobdiscoveryCompanies:               {Method: CloudjobdiscoveryCompanies, Actions: []string{"create", "delete", "get", "list", "update"}},
	CloudjobdiscoveryEvents:                  {Method: CloudjobdiscoveryEvents, Actions: []string{"create"}},
	CloudjobdiscoveryJobs:                    {Method: CloudjobdiscoveryJobs, Actions: []string{"create", "delete", "get", "search", "update"}},
	CloudjobdiscoveryProfiles:                {Method: CloudjobdiscoveryProfiles, Actions: []string{"create", "delete", "get", "search", "update"}},
	CloudjobdiscoveryTenants:                 {Method: CloudjobdiscoveryTenants, Actions: []string{"create", "delete", "get", "update"}},
	CloudjobdiscoveryTools:                   {Method: CloudjobdiscoveryTools, Actions: []string{"access"}},
	CloudkmsCryptoKeyVersions:                {Method: CloudkmsCryptoKeyVersions, Actions: []string{"create", "destroy", "get", "list", "restore", "update", "useToDecrypt", "useToEncrypt", "useToSign", "viewPublicKey"}},
	CloudkmsCryptoKeys:                       {Method: CloudkmsCryptoKeys, Actions: []string{"create", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	CloudkmsKeyRings:                         {Method: CloudkmsKeyRings, Actions: []string{"create", "get", "getIamPolicy", "list", "setIamPolicy"}},
	CloudmessagingMessages:                   {Method: CloudmessagingMessages, Actions: []string{"create"}},
	CloudmigrationVelostrataendpoints:        {Method: CloudmigrationVelostrataendpoints, Actions: []string{"connect"}},
	CloudnotificationsActivities:             {Method: CloudnotificationsActivities, Actions: []string{"list"}},
	CloudprivatecatalogTargets:               {Method: CloudprivatecatalogTargets, Actions: []string{"get"}},
	CloudprivatecatalogproducerTargets:       {Method: CloudprivatecatalogproducerTargets, Actions: []string{"associate", "unassociate"}},
	CloudprofilerProfiles:                    {Method: CloudprofilerProfiles, Actions: []string{"create", "list", "update"}},
	CloudschedulerJobs:                       {Method: CloudschedulerJobs, Actions: []string{"create", "delete", "enable", "fullView", "get", "list", "pause", "run", "update"}},
	CloudschedulerLocations:                  {Method: CloudschedulerLocations, Actions: []string{"get", "list"}},
	CloudsecurityscannerCrawledurls:          {Method: CloudsecurityscannerCrawledurls, Actions: []string{"list"}},
	CloudsecurityscannerResults:              {Method: CloudsecurityscannerResults, Actions: []string{"get", "list"}},
	CloudsecurityscannerScanruns:             {Method: CloudsecurityscannerScanruns, Actions: []string{"get", "getSummary", "list", "stop"}},
	CloudsecurityscannerScans:                {Method: CloudsecurityscannerScans, Actions: []string{"create", "delete", "get", "list", "run", "update"}},
	CloudsqlBackupRuns:                       {Method: CloudsqlBackupRuns, Actions: []string{"create", "delete", "get", "list"}},
	CloudsqlDatabases:                        {Method: CloudsqlDatabases, Actions: []string{"create", "delete", "get", "list", "update"}},
	CloudsqlInstances:                        {Method: CloudsqlInstances, Actions: []string{"addServerCa", "clone", "connect", "create", "delete", "demoteMaster", "export", "failover", "get", "import", "list", "listServerCas", "promoteReplica", "resetSslConfig", "restart", "restoreBackup", "rotateServerCa", "startReplica", "stopReplica", "truncateLog", "update"}},
	CloudsqlSslCerts:                         {Method: CloudsqlSslCerts, Actions: []string{"create", "createEphemeral", "delete", "get", "list"}},
	CloudsqlUsers:                            {Method: CloudsqlUsers, Actions: []string{"create", "delete", "list", "update"}},
	CloudtasksLocations:                      {Method: CloudtasksLocations, Actions: []string{"get", "list"}},
	CloudtasksQueues:                         {Method: CloudtasksQueues, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "pause", "purge", "resume", "setIamPolicy", "update"}},
	CloudtasksTasks:                          {Method: CloudtasksTasks, Actions: []string{"create", "delete", "fullView", "get", "list", "run"}},
	CloudtestserviceEnvironmentcatalog:       {Method: CloudtestserviceEnvironmentcatalog, Actions: []string{"get"}},
	CloudtestserviceMatrices:                 {Method: CloudtestserviceMatrices, Actions: []string{"create", "get", "update"}},
	CloudtoolresultsExecutions:               {Method: CloudtoolresultsExecutions, Actions: []string{"create", "get", "list", "update"}},
	CloudtoolresultsHistories:                {Method: CloudtoolresultsHistories, Actions: []string{"create", "get", "list"}},
	CloudtoolresultsSettings:                 {Method: CloudtoolresultsSettings, Actions: []string{"create", "get", "update"}},
	CloudtoolresultsSteps:                    {Method: CloudtoolresultsSteps, Actions: []string{"create", "get", "list", "update"}},
	CloudtraceInsights:                       {Method: CloudtraceInsights, Actions: []string{"get", "list"}},
	CloudtraceStats:                          {Method: CloudtraceStats, Actions: []string{"get"}},
	CloudtraceTasks:                          {Method: CloudtraceTasks, Actions: []string{"create", "delete", "get", "list"}},
	CloudtraceTraces:                         {Method: CloudtraceTraces, Actions: []string{"get", "list", "patch"}},
	CloudtranslateGeneralModels:              {Method: CloudtranslateGeneralModels, Actions: []string{"batchPredict", "get", "predict"}},
	CloudtranslateGlossaries:                 {Method: CloudtranslateGlossaries, Actions: []string{"batchPredict", "create", "delete", "get", "list", "predict"}},
	CloudtranslateLanguageDetectionModels:    {Method: CloudtranslateLanguageDetectionModels, Actions: []string{"predict"}},
	CloudtranslateLocations:                  {Method: CloudtranslateLocations, Actions: []string{"get", "list"}},
	CloudtranslateOperations:                 {Method: CloudtranslateOperations, Actions: []string{"cancel", "delete", "get", "list", "wait"}},
	ComposerEnvironments:                     {Method: ComposerEnvironments, Actions: []string{"create", "delete", "get", "list", "update"}},
	ComposerImageversions:                    {Method: ComposerImageversions, Actions: []string{"list"}},
	ComposerOperations:                       {Method: ComposerOperations, Actions: []string{"delete", "get", "list"}},
	ComputeAcceleratorTypes:                  {Method: ComputeAcceleratorTypes, Actions: []string{"get", "list"}},
	ComputeAddresses:                         {Method: ComputeAddresses, Actions: []string{"create", "createInternal", "delete", "deleteInternal", "get", "list", "setLabels", "use", "useInternal"}},
	ComputeAutoscalers:                       {Method: ComputeAutoscalers, Actions: []string{"create", "delete", "get", "list", "update"}},
	ComputeBackendBuckets:                    {Method: ComputeBackendBuckets, Actions: []string{"create", "delete", "get", "list", "update", "use"}},
	ComputeBackendServices:                   {Method: ComputeBackendServices, Actions: []string{"create", "delete", "get", "list", "setSecurityPolicy", "update", "use"}},
	ComputeCommitments:                       {Method: ComputeCommitments, Actions: []string{"create", "get", "list"}},
	ComputeDiskTypes:                         {Method: ComputeDiskTypes, Actions: []string{"get", "list"}},
	ComputeDisks:                             {Method: ComputeDisks, Actions: []string{"addResourcePolicies", "create", "createSnapshot", "delete", "get", "getIamPolicy", "list", "removeResourcePolicies", "resize", "setIamPolicy", "setLabels", "update", "use", "useReadOnly"}},
	ComputeFirewalls:                         {Method: ComputeFirewalls, Actions: []string{"create", "delete", "get", "list", "update"}},
	ComputeForwardingRules:                   {Method: ComputeForwardingRules, Actions: []string{"create", "delete", "get", "list", "setLabels", "setTarget"}},
	ComputeGlobalAddresses:                   {Method: ComputeGlobalAddresses, Actions: []string{"create", "createInternal", "delete", "deleteInternal", "get", "list", "setLabels", "use"}},
	ComputeGlobalForwardingRules:             {Method: ComputeGlobalForwardingRules, Actions: []string{"create", "delete", "get", "list", "setLabels", "setTarget"}},
	ComputeGlobalOperations:                  {Method: ComputeGlobalOperations, Actions: []string{"delete", "get", "getIamPolicy", "list", "setIamPolicy"}},
	ComputeHealthChecks:                      {Method: ComputeHealthChecks, Actions: []string{"create", "delete", "get", "list", "update", "use", "useReadOnly"}},
	ComputeHttpHealthChecks:                  {Method: ComputeHttpHealthChecks, Actions: []string{"create", "delete", "get", "list", "update", "use", "useReadOnly"}},
	ComputeHttpsHealthChecks:                 {Method: ComputeHttpsHealthChecks, Actions: []string{"create", "delete", "get", "list", "update", "use", "useReadOnly"}},
	ComputeImages:                            {Method: ComputeImages, Actions: []string{"create", "delete", "deprecate", "get", "getFromFamily", "getIamPolicy", "list", "setIamPolicy", "setLabels", "update", "useReadOnly"}},
	ComputeInstanceGroupManagers:             {Method: ComputeInstanceGroupManagers, Actions: []string{"create", "delete", "get", "list", "update", "use"}},
	ComputeInstanceGroups:                    {Method: ComputeInstanceGroups, Actions: []string{"create", "delete", "get", "list", "update", "use"}},
	ComputeInstanceTemplates:                 {Method: ComputeInstanceTemplates, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "useReadOnly"}},
	ComputeInstances:                         {Method: ComputeInstances, Actions: []string{"addAccessConfig", "addMaintenancePolicies", "attachDisk", "create", "delete", "deleteAccessConfig", "detachDisk", "get", "getGuestAttributes", "getIamPolicy", "getSerialPortOutput", "getShieldedInstanceIdentity", "getShieldedVmIdentity", "list", "listReferrers", "osAdminLogin", "osLogin", "removeMaintenancePolicies", "reset", "resume", "setDeletionProtection", "setDiskAutoDelete", "setIamPolicy", "setLabels", "setMachineResources", "setMachineType", "setMetadata", "setMinCpuPlatform", "setScheduling", "setServiceAccount", "setShieldedInstanceIntegrityPolicy", "setShieldedVmIntegrityPolicy", "setTags", "start", "startWithEncryptionKey", "stop", "suspend", "update", "updateAccessConfig", "updateDisplayDevice", "updateNetworkInterface", "updateShieldedInstanceConfig", "updateShieldedVmConfig", "use"}},
	ComputeInterconnectAttachments:           {Method: ComputeInterconnectAttachments, Actions: []string{"create", "delete", "get", "list", "setLabels", "update", "use"}},
	ComputeInterconnectLocations:             {Method: ComputeInterconnectLocations, Actions: []string{"get", "list"}},
	ComputeInterconnects:                     {Method: ComputeInterconnects, Actions: []string{"create", "delete", "get", "list", "setLabels", "update", "use"}},
	ComputeLicenseCodes:                      {Method: ComputeLicenseCodes, Actions: []string{"get", "getIamPolicy", "list", "setIamPolicy", "update", "use"}},
	ComputeLicenses:                          {Method: ComputeLicenses, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy"}},
	ComputeMachineTypes:                      {Method: ComputeMachineTypes, Actions: []string{"get", "list"}},
	ComputeMaintenancePolicies:               {Method: ComputeMaintenancePolicies, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "use"}},
	ComputeNetworkEndpointGroups:             {Method: ComputeNetworkEndpointGroups, Actions: []string{"attachNetworkEndpoints", "create", "delete", "detachNetworkEndpoints", "get", "getIamPolicy", "list", "setIamPolicy", "use"}},
	ComputeNetworks:                          {Method: ComputeNetworks, Actions: []string{"addPeering", "create", "delete", "get", "list", "removePeering", "switchToCustomMode", "update", "updatePeering", "updatePolicy", "use", "useExternalIp"}},
	ComputeNodeGroups:                        {Method: ComputeNodeGroups, Actions: []string{"addNodes", "create", "delete", "deleteNodes", "get", "getIamPolicy", "list", "setIamPolicy", "setNodeTemplate"}},
	ComputeNodeTemplates:                     {Method: ComputeNodeTemplates, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy"}},
	ComputeNodeTypes:                         {Method: ComputeNodeTypes, Actions: []string{"get", "list"}},
	ComputeProjects:                          {Method: ComputeProjects, Actions: []string{"get", "setDefaultNetworkTier", "setDefaultServiceAccount", "setUsageExportBucket"}},
	ComputeRegionBackendServices:             {Method: ComputeRegionBackendServices, Actions: []string{"create", "delete", "get", "list", "setSecurityPolicy", "update", "use"}},
	ComputeRegionOperations:                  {Method: ComputeRegionOperations, Actions: []string{"delete", "get", "getIamPolicy", "list", "setIamPolicy"}},
	ComputeRegions:                           {Method: ComputeRegions, Actions: []string{"get", "list"}},
	ComputeReservations:                      {Method: ComputeReservations, Actions: []string{"create", "delete", "get", "list", "resize"}},
	ComputeResourcePolicies:                  {Method: ComputeResourcePolicies, Actions: []string{"create", "delete", "get", "list", "use"}},
	ComputeRouters:                           {Method: ComputeRouters, Actions: []string{"create", "delete", "get", "list", "update", "use"}},
	ComputeRoutes:                            {Method: ComputeRoutes, Actions: []string{"create", "delete", "get", "list"}},
	ComputeSecurityPolicies:                  {Method: ComputeSecurityPolicies, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update", "use"}},
	ComputeSnapshots:                         {Method: ComputeSnapshots, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "setLabels", "useReadOnly"}},
	ComputeSslCertificates:                   {Method: ComputeSslCertificates, Actions: []string{"create", "delete", "get", "list"}},
	ComputeSslPolicies:                       {Method: ComputeSslPolicies, Actions: []string{"create", "delete", "get", "list", "listAvailableFeatures", "update", "use"}},
	ComputeSubnetworks:                       {Method: ComputeSubnetworks, Actions: []string{"create", "delete", "expandIpCidrRange", "get", "getIamPolicy", "list", "setIamPolicy", "setPrivateIpGoogleAccess", "update", "use", "useExternalIp"}},
	ComputeTargetHttpProxies:                 {Method: ComputeTargetHttpProxies, Actions: []string{"create", "delete", "get", "list", "setUrlMap", "use"}},
	ComputeTargetHttpsProxies:                {Method: ComputeTargetHttpsProxies, Actions: []string{"create", "delete", "get", "list", "setSslCertificates", "setSslPolicy", "setUrlMap", "use"}},
	ComputeTargetInstances:                   {Method: ComputeTargetInstances, Actions: []string{"create", "delete", "get", "list", "use"}},
	ComputeTargetPools:                       {Method: ComputeTargetPools, Actions: []string{"addHealthCheck", "addInstance", "create", "delete", "get", "list", "removeHealthCheck", "removeInstance", "update", "use"}},
	ComputeTargetSslProxies:                  {Method: ComputeTargetSslProxies, Actions: []string{"create", "delete", "get", "list", "setBackendService", "setProxyHeader", "setSslCertificates", "use"}},
	ComputeTargetTcpProxies:                  {Method: ComputeTargetTcpProxies, Actions: []string{"create", "delete", "get", "list", "update", "use"}},
	ComputeTargetVpnGateways:                 {Method: ComputeTargetVpnGateways, Actions: []string{"create", "delete", "get", "list", "setLabels", "use"}},
	ComputeUrlMaps:                           {Method: ComputeUrlMaps, Actions: []string{"create", "delete", "get", "invalidateCache", "list", "update", "use", "validate"}},
	ComputeVpnGateways:                       {Method: ComputeVpnGateways, Actions: []string{"create", "delete", "get", "list", "setLabels", "use"}},
	ComputeVpnTunnels:                        {Method: ComputeVpnTunnels, Actions: []string{"create", "delete", "get", "list", "setLabels"}},
	ComputeZoneOperations:                    {Method: ComputeZoneOperations, Actions: []string{"delete", "get", "getIamPolicy", "list", "setIamPolicy"}},
	ComputeZones:                             {Method: ComputeZones, Actions: []string{"get", "list"}},
	ContainerApiServices:                     {Method: ContainerApiServices, Actions: []string{"create", "delete", "get", "list", "update", "updateStatus"}},
	ContainerBackendConfigs:                  {Method: ContainerBackendConfigs, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerBindings:                        {Method: ContainerBindings, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerCertificateSigningRequests:      {Method: ContainerCertificateSigningRequests, Actions: []string{"approve", "create", "delete", "get", "list", "update", "updateStatus"}},
	ContainerClusterRoleBindings:             {Method: ContainerClusterRoleBindings, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerClusterRoles:                    {Method: ContainerClusterRoles, Actions: []string{"bind", "create", "delete", "get", "list", "update"}},
	ContainerClusters:                        {Method: ContainerClusters, Actions: []string{"create", "delete", "get", "getCredentials", "list", "update"}},
	ContainerComponentStatuses:               {Method: ContainerComponentStatuses, Actions: []string{"get", "list"}},
	ContainerConfigMaps:                      {Method: ContainerConfigMaps, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerControllerRevisions:             {Method: ContainerControllerRevisions, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerCronJobs:                        {Method: ContainerCronJobs, Actions: []string{"create", "delete", "get", "getStatus", "list", "update", "updateStatus"}},
	ContainerCustomResourceDefinitions:       {Method: ContainerCustomResourceDefinitions, Actions: []string{"create", "delete", "get", "list", "update", "updateStatus"}},
	ContainerDaemonSets:                      {Method: ContainerDaemonSets, Actions: []string{"create", "delete", "get", "getStatus", "list", "update", "updateStatus"}},
	ContainerDeployments:                     {Method: ContainerDeployments, Actions: []string{"create", "delete", "get", "getScale", "getStatus", "list", "rollback", "update", "updateScale", "updateStatus"}},
	ContainerEndpoints:                       {Method: ContainerEndpoints, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerEvents:                          {Method: ContainerEvents, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerHorizontalPodAutoscalers:        {Method: ContainerHorizontalPodAutoscalers, Actions: []string{"create", "delete", "get", "getStatus", "list", "update", "updateStatus"}},
	ContainerIngresses:                       {Method: ContainerIngresses, Actions: []string{"create", "delete", "get", "getStatus", "list", "update", "updateStatus"}},
	ContainerInitializerConfigurations:       {Method: ContainerInitializerConfigurations, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerJobs:                            {Method: ContainerJobs, Actions: []string{"create", "delete", "get", "getStatus", "list", "update", "updateStatus"}},
	ContainerLimitRanges:                     {Method: ContainerLimitRanges, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerLocalSubjectAccessReviews:       {Method: ContainerLocalSubjectAccessReviews, Actions: []string{"create", "list"}},
	ContainerNamespaces:                      {Method: ContainerNamespaces, Actions: []string{"create", "delete", "get", "getStatus", "list", "update", "updateStatus"}},
	ContainerNetworkPolicies:                 {Method: ContainerNetworkPolicies, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerNodes:                           {Method: ContainerNodes, Actions: []string{"create", "delete", "get", "getStatus", "list", "proxy", "update", "updateStatus"}},
	ContainerOperations:                      {Method: ContainerOperations, Actions: []string{"get", "list"}},
	ContainerPersistentVolumeClaims:          {Method: ContainerPersistentVolumeClaims, Actions: []string{"create", "delete", "get", "getStatus", "list", "update", "updateStatus"}},
	ContainerPersistentVolumes:               {Method: ContainerPersistentVolumes, Actions: []string{"create", "delete", "get", "getStatus", "list", "update", "updateStatus"}},
	ContainerPetSets:                         {Method: ContainerPetSets, Actions: []string{"create", "delete", "get", "list", "update", "updateStatus"}},
	ContainerPodDisruptionBudgets:            {Method: ContainerPodDisruptionBudgets, Actions: []string{"create", "delete", "get", "getStatus", "list", "update", "updateStatus"}},
	ContainerPodPresets:                      {Method: ContainerPodPresets, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerPodSecurityPolicies:             {Method: ContainerPodSecurityPolicies, Actions: []string{"create", "delete", "get", "list", "update", "use"}},
	ContainerPodTemplates:                    {Method: ContainerPodTemplates, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerPods:                            {Method: ContainerPods, Actions: []string{"attach", "create", "delete", "evict", "exec", "get", "getLogs", "getStatus", "initialize", "list", "portForward", "proxy", "update", "updateStatus"}},
	ContainerReplicaSets:                     {Method: ContainerReplicaSets, Actions: []string{"create", "delete", "get", "getScale", "getStatus", "list", "update", "updateScale", "updateStatus"}},
	ContainerReplicationControllers:          {Method: ContainerReplicationControllers, Actions: []string{"create", "delete", "get", "getScale", "getStatus", "list", "update", "updateScale", "updateStatus"}},
	ContainerResourceQuotas:                  {Method: ContainerResourceQuotas, Actions: []string{"create", "delete", "get", "getStatus", "list", "update", "updateStatus"}},
	ContainerRoleBindings:                    {Method: ContainerRoleBindings, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerRoles:                           {Method: ContainerRoles, Actions: []string{"bind", "create", "delete", "get", "list", "update"}},
	ContainerScheduledJobs:                   {Method: ContainerScheduledJobs, Actions: []string{"create", "delete", "get", "list", "update", "updateStatus"}},
	ContainerSecrets:                         {Method: ContainerSecrets, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerSelfSubjectAccessReviews:        {Method: ContainerSelfSubjectAccessReviews, Actions: []string{"create", "list"}},
	ContainerServiceAccounts:                 {Method: ContainerServiceAccounts, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerServices:                        {Method: ContainerServices, Actions: []string{"create", "delete", "get", "getStatus", "list", "proxy", "update", "updateStatus"}},
	ContainerStatefulSets:                    {Method: ContainerStatefulSets, Actions: []string{"create", "delete", "get", "getScale", "getStatus", "list", "update", "updateScale", "updateStatus"}},
	ContainerStorageClasses:                  {Method: ContainerStorageClasses, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerSubjectAccessReviews:            {Method: ContainerSubjectAccessReviews, Actions: []string{"create", "list"}},
	ContainerThirdPartyObjects:               {Method: ContainerThirdPartyObjects, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerThirdPartyResources:             {Method: ContainerThirdPartyResources, Actions: []string{"create", "delete", "get", "list", "update"}},
	ContainerTokenReviews:                    {Method: ContainerTokenReviews, Actions: []string{"create"}},
	DatacatalogEntries:                       {Method: DatacatalogEntries, Actions: []string{"create", "delete", "get", "getIamPolicy", "setIamPolicy", "update"}},
	DatacatalogEntryGroups:                   {Method: DatacatalogEntryGroups, Actions: []string{"create", "delete", "get", "getIamPolicy", "setIamPolicy"}},
	DatacatalogTagTemplates:                  {Method: DatacatalogTagTemplates, Actions: []string{"create", "delete", "get", "getIamPolicy", "getTag", "setIamPolicy", "update", "use"}},
	DataflowJobs:                             {Method: DataflowJobs, Actions: []string{"cancel", "create", "get", "list", "updateContents"}},
	DataflowMessages:                         {Method: DataflowMessages, Actions: []string{"list"}},
	DataflowMetrics:                          {Method: DataflowMetrics, Actions: []string{"get"}},
	DatafusionInstances:                      {Method: DatafusionInstances, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "restart", "setIamPolicy", "update", "upgrade"}},
	DatafusionLocations:                      {Method: DatafusionLocations, Actions: []string{"get", "list"}},
	DatafusionOperations:                     {Method: DatafusionOperations, Actions: []string{"cancel", "get", "list"}},
	DatalabelingAnnotateddatasets:            {Method: DatalabelingAnnotateddatasets, Actions: []string{"delete", "get", "label", "list"}},
	DatalabelingAnnotationspecsets:           {Method: DatalabelingAnnotationspecsets, Actions: []string{"create", "delete", "get", "list"}},
	DatalabelingDataitems:                    {Method: DatalabelingDataitems, Actions: []string{"get", "list"}},
	DatalabelingDatasets:                     {Method: DatalabelingDatasets, Actions: []string{"create", "delete", "export", "get", "import", "list"}},
	DatalabelingExamples:                     {Method: DatalabelingExamples, Actions: []string{"get", "list"}},
	DatalabelingInstructions:                 {Method: DatalabelingInstructions, Actions: []string{"create", "delete", "get", "list"}},
	DatalabelingOperations:                   {Method: DatalabelingOperations, Actions: []string{"cancel", "get", "list"}},
	DataprepProjects:                         {Method: DataprepProjects, Actions: []string{"use"}},
	DataprocAgents:                           {Method: DataprocAgents, Actions: []string{"create", "delete", "get", "list", "update"}},
	DataprocClusters:                         {Method: DataprocClusters, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update", "use"}},
	DataprocJobs:                             {Method: DataprocJobs, Actions: []string{"cancel", "create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	DataprocOperations:                       {Method: DataprocOperations, Actions: []string{"cancel", "delete", "get", "getIamPolicy", "list", "setIamPolicy"}},
	DataprocTasks:                            {Method: DataprocTasks, Actions: []string{"lease", "listInvalidatedLeases", "reportStatus"}},
	DataprocWorkflowTemplates:                {Method: DataprocWorkflowTemplates, Actions: []string{"create", "delete", "get", "getIamPolicy", "instantiate", "instantiateInline", "list", "setIamPolicy", "update"}},
	DatastoreDatabases:                       {Method: DatastoreDatabases, Actions: []string{"create", "delete", "export", "get", "getIamPolicy", "import", "list", "setIamPolicy", "update"}},
	DatastoreEntities:                        {Method: DatastoreEntities, Actions: []string{"allocateIds", "create", "delete", "get", "list", "update"}},
	DatastoreIndexes:                         {Method: DatastoreIndexes, Actions: []string{"create", "delete", "get", "list", "update"}},
	DatastoreLocations:                       {Method: DatastoreLocations, Actions: []string{"get", "list"}},
	DatastoreNamespaces:                      {Method: DatastoreNamespaces, Actions: []string{"get", "getIamPolicy", "list", "setIamPolicy"}},
	DatastoreOperations:                      {Method: DatastoreOperations, Actions: []string{"cancel", "delete", "get", "list"}},
	DatastoreStatistics:                      {Method: DatastoreStatistics, Actions: []string{"get", "list"}},
	DeploymentmanagerCompositeTypes:          {Method: DeploymentmanagerCompositeTypes, Actions: []string{"create", "delete", "get", "list", "update"}},
	DeploymentmanagerDeployments:             {Method: DeploymentmanagerDeployments, Actions: []string{"cancelPreview", "create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "stop", "update"}},
	DeploymentmanagerManifests:               {Method: DeploymentmanagerManifests, Actions: []string{"get", "list"}},
	DeploymentmanagerOperations:              {Method: DeploymentmanagerOperations, Actions: []string{"get", "list"}},
	DeploymentmanagerResources:               {Method: DeploymentmanagerResources, Actions: []string{"get", "list"}},
	DeploymentmanagerTypeProviders:           {Method: DeploymentmanagerTypeProviders, Actions: []string{"create", "delete", "get", "getType", "list", "listTypes", "update"}},
	DeploymentmanagerTypes:                   {Method: DeploymentmanagerTypes, Actions: []string{"create", "delete", "get", "list", "update"}},
	DialogflowAgents:                         {Method: DialogflowAgents, Actions: []string{"create", "delete", "export", "get", "import", "restore", "search", "train", "update"}},
	DialogflowContexts:                       {Method: DialogflowContexts, Actions: []string{"create", "delete", "get", "list", "update"}},
	DialogflowEntityTypes:                    {Method: DialogflowEntityTypes, Actions: []string{"create", "createEntity", "delete", "deleteEntity", "get", "list", "update", "updateEntity"}},
	DialogflowIntents:                        {Method: DialogflowIntents, Actions: []string{"create", "delete", "get", "list", "update"}},
	DialogflowOperations:                     {Method: DialogflowOperations, Actions: []string{"get"}},
	DialogflowSessionEntityTypes:             {Method: DialogflowSessionEntityTypes, Actions: []string{"create", "delete", "get", "list", "update"}},
	DialogflowSessions:                       {Method: DialogflowSessions, Actions: []string{"detectIntent", "streamingDetectIntent"}},
	DlpAnalyzeRiskTemplates:                  {Method: DlpAnalyzeRiskTemplates, Actions: []string{"create", "delete", "get", "list", "update"}},
	DlpDeidentifyTemplates:                   {Method: DlpDeidentifyTemplates, Actions: []string{"create", "delete", "get", "list", "update"}},
	DlpInspectTemplates:                      {Method: DlpInspectTemplates, Actions: []string{"create", "delete", "get", "list", "update"}},
	DlpJobTriggers:                           {Method: DlpJobTriggers, Actions: []string{"create", "delete", "get", "list", "update"}},
	DlpJobs:                                  {Method: DlpJobs, Actions: []string{"cancel", "create", "delete", "get", "list"}},
	DlpKms:                                   {Method: DlpKms, Actions: []string{"encrypt"}},
	DlpStoredInfoTypes:                       {Method: DlpStoredInfoTypes, Actions: []string{"create", "delete", "get", "list", "update"}},
	DnsChanges:                               {Method: DnsChanges, Actions: []string{"create", "get", "list"}},
	DnsDnsKeys:                               {Method: DnsDnsKeys, Actions: []string{"get", "list"}},
	DnsManagedZoneOperations:                 {Method: DnsManagedZoneOperations, Actions: []string{"get", "list"}},
	DnsManagedZones:                          {Method: DnsManagedZones, Actions: []string{"create", "delete", "get", "list", "update"}},
	DnsNetworks:                              {Method: DnsNetworks, Actions: []string{"bindPrivateDNSPolicy", "bindPrivateDNSZone", "targetWithPeeringZone"}},
	DnsPolicies:                              {Method: DnsPolicies, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	DnsProjects:                              {Method: DnsProjects, Actions: []string{"get"}},
	DnsResourceRecordSets:                    {Method: DnsResourceRecordSets, Actions: []string{"create", "delete", "list", "update"}},
	EndpointsPortals:                         {Method: EndpointsPortals, Actions: []string{"attachCustomDomain", "detachCustomDomain", "listCustomDomains", "update"}},
	ErrorreportingApplications:               {Method: ErrorreportingApplications, Actions: []string{"list"}},
	ErrorreportingErrorEvents:                {Method: ErrorreportingErrorEvents, Actions: []string{"create", "delete", "list"}},
	ErrorreportingGroupMetadata:              {Method: ErrorreportingGroupMetadata, Actions: []string{"get", "update"}},
	ErrorreportingGroups:                     {Method: ErrorreportingGroups, Actions: []string{"list"}},
	FileInstances:                            {Method: FileInstances, Actions: []string{"create", "delete", "get", "list", "restore", "update"}},
	FileLocations:                            {Method: FileLocations, Actions: []string{"get", "list"}},
	FileOperations:                           {Method: FileOperations, Actions: []string{"cancel", "delete", "get", "list"}},
	FileSnapshots:                            {Method: FileSnapshots, Actions: []string{"create", "delete", "get", "list", "update"}},
	FirebaseBillingPlans:                     {Method: FirebaseBillingPlans, Actions: []string{"get", "update"}},
	FirebaseClients:                          {Method: FirebaseClients, Actions: []string{"create", "delete", "get"}},
	FirebaseLinks:                            {Method: FirebaseLinks, Actions: []string{"create", "delete", "list", "update"}},
	FirebaseProjects:                         {Method: FirebaseProjects, Actions: []string{"delete", "get", "update"}},
	FirebaseabtExperimentresults:             {Method: FirebaseabtExperimentresults, Actions: []string{"get"}},
	FirebaseabtExperiments:                   {Method: FirebaseabtExperiments, Actions: []string{"create", "delete", "get", "list", "update"}},
	FirebaseabtProjectmetadata:               {Method: FirebaseabtProjectmetadata, Actions: []string{"get"}},
	FirebaseanalyticsResources:               {Method: FirebaseanalyticsResources, Actions: []string{"googleAnalyticsEdit", "googleAnalyticsReadAndAnalyze"}},
	FirebaseauthConfigs:                      {Method: FirebaseauthConfigs, Actions: []string{"create", "get", "getHashConfig", "update"}},
	FirebaseauthUsers:                        {Method: FirebaseauthUsers, Actions: []string{"create", "createSession", "delete", "get", "sendEmail", "update"}},
	FirebasecrashIssues:                      {Method: FirebasecrashIssues, Actions: []string{"update"}},
	FirebasecrashReports:                     {Method: FirebasecrashReports, Actions: []string{"get"}},
	FirebasecrashlyticsConfig:                {Method: FirebasecrashlyticsConfig, Actions: []string{"get", "update"}},
	FirebasecrashlyticsData:                  {Method: FirebasecrashlyticsData, Actions: []string{"get"}},
	FirebasecrashlyticsIssues:                {Method: FirebasecrashlyticsIssues, Actions: []string{"get", "list", "update"}},
	FirebasecrashlyticsSessions:              {Method: FirebasecrashlyticsSessions, Actions: []string{"get"}},
	FirebasedatabaseInstances:                {Method: FirebasedatabaseInstances, Actions: []string{"create", "get", "list", "update"}},
	FirebasedynamiclinksDestinations:         {Method: FirebasedynamiclinksDestinations, Actions: []string{"list", "update"}},
	FirebasedynamiclinksDomains:              {Method: FirebasedynamiclinksDomains, Actions: []string{"create", "delete", "get", "list", "update"}},
	FirebasedynamiclinksLinks:                {Method: FirebasedynamiclinksLinks, Actions: []string{"create", "get", "list", "update"}},
	FirebasedynamiclinksStats:                {Method: FirebasedynamiclinksStats, Actions: []string{"get"}},
	FirebaseextensionsConfigs:                {Method: FirebaseextensionsConfigs, Actions: []string{"create", "delete", "list", "update"}},
	FirebasehostingSites:                     {Method: FirebasehostingSites, Actions: []string{"create", "delete", "get", "list", "update"}},
	FirebaseinappmessagingCampaigns:          {Method: FirebaseinappmessagingCampaigns, Actions: []string{"create", "delete", "get", "list", "update"}},
	FirebasemlCompressionjobs:                {Method: FirebasemlCompressionjobs, Actions: []string{"create", "delete", "get", "list", "start", "update"}},
	FirebasemlModels:                         {Method: FirebasemlModels, Actions: []string{"create", "delete", "get", "list"}},
	FirebasemlModelversions:                  {Method: FirebasemlModelversions, Actions: []string{"create", "get", "list", "update"}},
	FirebasenotificationsMessages:            {Method: FirebasenotificationsMessages, Actions: []string{"create", "delete", "get", "list", "update"}},
	FirebaseperformanceConfig:                {Method: FirebaseperformanceConfig, Actions: []string{"create", "delete", "update"}},
	FirebaseperformanceData:                  {Method: FirebaseperformanceData, Actions: []string{"get"}},
	FirebasepredictionsPredictions:           {Method: FirebasepredictionsPredictions, Actions: []string{"create", "delete", "list", "update"}},
	FirebaserulesReleases:                    {Method: FirebaserulesReleases, Actions: []string{"create", "delete", "get", "getExecutable", "list", "update"}},
	FirebaserulesRulesets:                    {Method: FirebaserulesRulesets, Actions: []string{"create", "delete", "get", "list", "test"}},
	GenomicsDatasets:                         {Method: GenomicsDatasets, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	GenomicsOperations:                       {Method: GenomicsOperations, Actions: []string{"cancel", "create", "get", "list"}},
	HealthcareDatasets:                       {Method: HealthcareDatasets, Actions: []string{"create", "deidentify", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	HealthcareDicomStores:                    {Method: HealthcareDicomStores, Actions: []string{"create", "delete", "dicomWebDelete", "dicomWebRead", "dicomWebWrite", "export", "get", "getIamPolicy", "import", "list", "setIamPolicy", "update"}},
	HealthcareFhirResources:                  {Method: HealthcareFhirResources, Actions: []string{"create", "delete", "get", "patch", "purge", "update"}},
	HealthcareFhirStores:                     {Method: HealthcareFhirStores, Actions: []string{"create", "delete", "export", "get", "getIamPolicy", "import", "list", "searchResources", "setIamPolicy", "update"}},
	HealthcareHl7V2Messages:                  {Method: HealthcareHl7V2Messages, Actions: []string{"create", "delete", "get", "ingest", "list", "update"}},
	HealthcareHl7V2Stores:                    {Method: HealthcareHl7V2Stores, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	HealthcareOperations:                     {Method: HealthcareOperations, Actions: []string{"cancel", "get", "list"}},
	IamRoles:                                 {Method: IamRoles, Actions: []string{"create", "delete", "get", "list", "undelete", "update"}},
	IamServiceAccountKeys:                    {Method: IamServiceAccountKeys, Actions: []string{"create", "delete", "get", "list"}},
	IamServiceAccounts:                       {Method: IamServiceAccounts, Actions: []string{"actAs", "create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	IapTunnel:                                {Method: IapTunnel, Actions: []string{"getIamPolicy", "setIamPolicy"}},
	IapTunnelInstances:                       {Method: IapTunnelInstances, Actions: []string{"accessViaIAP", "getIamPolicy", "setIamPolicy"}},
	IapTunnelZones:                           {Method: IapTunnelZones, Actions: []string{"getIamPolicy", "setIamPolicy"}},
	IapWeb:                                   {Method: IapWeb, Actions: []string{"getIamPolicy", "setIamPolicy"}},
	IapWebServiceVersions:                    {Method: IapWebServiceVersions, Actions: []string{"getIamPolicy", "setIamPolicy"}},
	IapWebServices:                           {Method: IapWebServices, Actions: []string{"getIamPolicy", "setIamPolicy"}},
	IapWebTypes:                              {Method: IapWebTypes, Actions: []string{"getIamPolicy", "setIamPolicy"}},
	LoggingExclusions:                        {Method: LoggingExclusions, Actions: []string{"create", "delete", "get", "list", "update"}},
	LoggingLogEntries:                        {Method: LoggingLogEntries, Actions: []string{"create", "list"}},
	LoggingLogMetrics:                        {Method: LoggingLogMetrics, Actions: []string{"create", "delete", "get", "list", "update"}},
	LoggingLogServiceIndexes:                 {Method: LoggingLogServiceIndexes, Actions: []string{"list"}},
	LoggingLogServices:                       {Method: LoggingLogServices, Actions: []string{"list"}},
	LoggingLogs:                              {Method: LoggingLogs, Actions: []string{"delete", "list"}},
	LoggingPrivateLogEntries:                 {Method: LoggingPrivateLogEntries, Actions: []string{"list"}},
	LoggingSinks:                             {Method: LoggingSinks, Actions: []string{"create", "delete", "get", "list", "update"}},
	LoggingUsage:                             {Method: LoggingUsage, Actions: []string{"get"}},
	ManagedidentitiesDomains:                 {Method: ManagedidentitiesDomains, Actions: []string{"attachTrust", "create", "delete", "detachTrust", "get", "getIamPolicy", "list", "reconfigureTrust", "resetpassword", "setIamPolicy", "update", "validateTrust"}},
	ManagedidentitiesLocations:               {Method: ManagedidentitiesLocations, Actions: []string{"get", "list"}},
	ManagedidentitiesOperations:              {Method: ManagedidentitiesOperations, Actions: []string{"cancel", "delete", "get", "list"}},
	MlJobs:                                   {Method: MlJobs, Actions: []string{"cancel", "create", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	MlLocations:                              {Method: MlLocations, Actions: []string{"get", "list"}},
	MlModels:                                 {Method: MlModels, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "predict", "setIamPolicy", "update"}},
	MlOperations:                             {Method: MlOperations, Actions: []string{"cancel", "get", "list"}},
	MlProjects:                               {Method: MlProjects, Actions: []string{"getConfig"}},
	MlVersions:                               {Method: MlVersions, Actions: []string{"create", "delete", "get", "list", "predict", "update"}},
	MonitoringAlertPolicies:                  {Method: MonitoringAlertPolicies, Actions: []string{"create", "delete", "get", "list", "update"}},
	MonitoringDashboards:                     {Method: MonitoringDashboards, Actions: []string{"create", "delete", "get", "list", "update"}},
	MonitoringGroups:                         {Method: MonitoringGroups, Actions: []string{"create", "delete", "get", "list", "update"}},
	MonitoringMetricDescriptors:              {Method: MonitoringMetricDescriptors, Actions: []string{"create", "delete", "get", "list"}},
	MonitoringMonitoredResourceDescriptors:   {Method: MonitoringMonitoredResourceDescriptors, Actions: []string{"get", "list"}},
	MonitoringNotificationChannelDescriptors: {Method: MonitoringNotificationChannelDescriptors, Actions: []string{"get", "list"}},
	MonitoringNotificationChannels:           {Method: MonitoringNotificationChannels, Actions: []string{"create", "delete", "get", "getVerificationCode", "list", "sendVerificationCode", "update", "verify"}},
	MonitoringPublicWidgets:                  {Method: MonitoringPublicWidgets, Actions: []string{"create", "delete", "get", "list", "update"}},
	MonitoringTimeSeries:                     {Method: MonitoringTimeSeries, Actions: []string{"create", "list"}},
	MonitoringUptimeCheckConfigs:             {Method: MonitoringUptimeCheckConfigs, Actions: []string{"create", "delete", "get", "list", "update"}},
	OrgpolicyPolicy:                          {Method: OrgpolicyPolicy, Actions: []string{"get"}},
	ProximitybeaconAttachments:               {Method: ProximitybeaconAttachments, Actions: []string{"create", "delete", "get", "list"}},
	ProximitybeaconBeacons:                   {Method: ProximitybeaconBeacons, Actions: []string{"attach", "create", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	ProximitybeaconNamespaces:                {Method: ProximitybeaconNamespaces, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	PubsubSnapshots:                          {Method: PubsubSnapshots, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "seek", "setIamPolicy", "update"}},
	PubsubSubscriptions:                      {Method: PubsubSubscriptions, Actions: []string{"consume", "create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	PubsubTopics:                             {Method: PubsubTopics, Actions: []string{"attachSubscription", "create", "delete", "get", "getIamPolicy", "list", "publish", "setIamPolicy", "update", "updateTag"}},
	RedisInstances:                           {Method: RedisInstances, Actions: []string{"create", "delete", "export", "get", "import", "list", "update"}},
	RedisLocations:                           {Method: RedisLocations, Actions: []string{"get", "list"}},
	RedisOperations:                          {Method: RedisOperations, Actions: []string{"cancel", "delete", "get", "list"}},
	RemotebuildexecutionActions:              {Method: RemotebuildexecutionActions, Actions: []string{"create", "get", "update"}},
	RemotebuildexecutionBlobs:                {Method: RemotebuildexecutionBlobs, Actions: []string{"create", "get"}},
	RemotebuildexecutionBotsessions:          {Method: RemotebuildexecutionBotsessions, Actions: []string{"create", "update"}},
	RemotebuildexecutionInstances:            {Method: RemotebuildexecutionInstances, Actions: []string{"create", "delete", "get", "list"}},
	RemotebuildexecutionLogstreams:           {Method: RemotebuildexecutionLogstreams, Actions: []string{"create", "get", "update"}},
	RemotebuildexecutionWorkerpools:          {Method: RemotebuildexecutionWorkerpools, Actions: []string{"create", "delete", "get", "list", "update"}},
	ResourcemanagerProjects:                  {Method: ResourcemanagerProjects, Actions: []string{"createBillingAssignment", "delete", "deleteBillingAssignment", "get", "getIamPolicy", "setIamPolicy", "undelete", "update", "updateLiens"}},
	RunConfigurations:                        {Method: RunConfigurations, Actions: []string{"get", "list"}},
	RunLocations:                             {Method: RunLocations, Actions: []string{"list"}},
	RunRevisions:                             {Method: RunRevisions, Actions: []string{"delete", "get", "list"}},
	RunRoutes:                                {Method: RunRoutes, Actions: []string{"get", "invoke", "list"}},
	RunServices:                              {Method: RunServices, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	RuntimeconfigConfigs:                     {Method: RuntimeconfigConfigs, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	RuntimeconfigOperations:                  {Method: RuntimeconfigOperations, Actions: []string{"get", "list"}},
	RuntimeconfigVariables:                   {Method: RuntimeconfigVariables, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update", "watch"}},
	RuntimeconfigWaiters:                     {Method: RuntimeconfigWaiters, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	ServicebrokerBindingoperations:           {Method: ServicebrokerBindingoperations, Actions: []string{"get", "list"}},
	ServicebrokerBindings:                    {Method: ServicebrokerBindings, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy"}},
	ServicebrokerCatalogs:                    {Method: ServicebrokerCatalogs, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "validate"}},
	ServicebrokerInstanceoperations:          {Method: ServicebrokerInstanceoperations, Actions: []string{"get", "list"}},
	ServicebrokerInstances:                   {Method: ServicebrokerInstances, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	ServiceconsumermanagementConsumers:       {Method: ServiceconsumermanagementConsumers, Actions: []string{"get"}},
	ServiceconsumermanagementQuota:           {Method: ServiceconsumermanagementQuota, Actions: []string{"get", "update"}},
	ServiceconsumermanagementTenancyu:        {Method: ServiceconsumermanagementTenancyu, Actions: []string{"addResource", "create", "delete", "list", "removeResource"}},
	ServicemanagementServices:                {Method: ServicemanagementServices, Actions: []string{"bind", "check", "create", "delete", "get", "getIamPolicy", "list", "quota", "report", "setIamPolicy", "update"}},
	ServicenetworkingOperations:              {Method: ServicenetworkingOperations, Actions: []string{"cancel", "delete", "get", "list"}},
	ServicenetworkingServices:                {Method: ServicenetworkingServices, Actions: []string{"addPeering", "addSubnetwork", "get"}},
	ServiceusageApiKeys:                      {Method: ServiceusageApiKeys, Actions: []string{"create", "delete", "get", "getProjectForKey", "list", "regenerate", "revert", "update"}},
	ServiceusageOperations:                   {Method: ServiceusageOperations, Actions: []string{"cancel", "delete", "get", "list"}},
	ServiceusageQuotas:                       {Method: ServiceusageQuotas, Actions: []string{"get", "update"}},
	ServiceusageServices:                     {Method: ServiceusageServices, Actions: []string{"disable", "enable", "get", "list", "use"}},
	SourceRepos:                              {Method: SourceRepos, Actions: []string{"create", "delete", "get", "getIamPolicy", "getProjectConfig", "list", "setIamPolicy", "update", "updateProjectConfig", "updateRepoConfig"}},
	SpannerDatabaseOperations:                {Method: SpannerDatabaseOperations, Actions: []string{"cancel", "delete", "get", "list"}},
	SpannerDatabases:                         {Method: SpannerDatabases, Actions: []string{"beginOrRollbackReadWriteTransaction", "beginReadOnlyTransaction", "create", "drop", "get", "getDdl", "getIamPolicy", "list", "read", "select", "setIamPolicy", "update", "updateDdl", "write"}},
	SpannerInstanceConfigs:                   {Method: SpannerInstanceConfigs, Actions: []string{"get", "list"}},
	SpannerInstanceOperations:                {Method: SpannerInstanceOperations, Actions: []string{"cancel", "delete", "get", "list"}},
	SpannerInstances:                         {Method: SpannerInstances, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	SpannerSessions:                          {Method: SpannerSessions, Actions: []string{"create", "delete", "get", "list"}},
	StackdriverProjects:                      {Method: StackdriverProjects, Actions: []string{"edit", "get"}},
	StackdriverResourceMetadata:              {Method: StackdriverResourceMetadata, Actions: []string{"write"}},
	StorageBuckets:                           {Method: StorageBuckets, Actions: []string{"create", "delete", "list"}},
	StorageObjects:                           {Method: StorageObjects, Actions: []string{"create", "delete", "get", "getIamPolicy", "list", "setIamPolicy", "update"}},
	StorageHmacKeys:                          {Method: StorageHmacKeys, Actions: []string{"create", "delete", "get", "list", "update"}},
	StoragetransferJobs:                      {Method: StoragetransferJobs, Actions: []string{"create", "delete", "get", "list", "update"}},
	StoragetransferOperations:                {Method: StoragetransferOperations, Actions: []string{"cancel", "get", "list", "pause", "resume"}},
	StoragetransferProjects:                  {Method: StoragetransferProjects, Actions: []string{"getServiceAccount"}},
	SubscribewithgoogledeveloperTools:        {Method: SubscribewithgoogledeveloperTools, Actions: []string{"get"}},
	ThreatdetectionDetectorSettings:          {Method: ThreatdetectionDetectorSettings, Actions: []string{"clear", "get", "update"}},
	TpuAcceleratortypes:                      {Method: TpuAcceleratortypes, Actions: []string{"get", "list"}},
	TpuLocations:                             {Method: TpuLocations, Actions: []string{"get", "list"}},
	TpuNodes:                                 {Method: TpuNodes, Actions: []string{"create", "delete", "get", "list", "reimage", "reset", "start", "stop"}},
	TpuOperations:                            {Method: TpuOperations, Actions: []string{"get", "list"}},
	TpuTensorflowversions:                    {Method: TpuTensorflowversions, Actions: []string{"get", "list"}},
	VpcaccessConnectors:                      {Method: VpcaccessConnectors, Actions: []string{"create", "delete", "get", "list", "use"}},
	VpcaccessLocations:                       {Method: VpcaccessLocations, Actions: []string{"list"}},
	VpcaccessOperations:                      {Method: VpcaccessOperations, Actions: []string{"get", "list"}},
}
