package cmd

import (
	"github.com/securisec/cliam/aws"
	"github.com/securisec/cliam/shared"
)

// AwsServiceGrouping common service mappings to group services together
var AwsServiceGrouping = map[string][]string{
	"common": {
		aws.Lambda,
		aws.IAM,
		aws.S3,
		aws.APIGateway,
		aws.EC2,
	},
	"compute": {
		aws.Lambda,
		aws.EC2,
		aws.ElasticBeanStalk,
		aws.ElasticFileSystem,
		aws.ELB,
	},
	"databases": {
		aws.RDS,
		aws.Redshift,
		aws.Dynamodb,
	},
	"containers": {
		aws.ECS,
		aws.EKS,
	},
	"serverless": {
		aws.APIGateway,
		aws.Lambda,
		aws.S3,
		aws.SNS,
		aws.SQS,
		aws.Dynamodb,
		aws.SecretsManager,
	},
	"storage": {
		aws.S3,
		aws.Snowball,
		aws.StorageGateway,
		aws.ElasticFileSystem,
	},
	"all": {
		aws.ACM,
		aws.APIGateway,
		aws.AccessAnalyzers,
		aws.AppFlow,
		aws.AppRunner,
		aws.AppStream,
		aws.AppSync,
		aws.Athena,
		aws.AuditManager,
		aws.AutoScaling,
		aws.Backup,
		aws.BackupGateway,
		aws.Batch,
		aws.Chime,
		aws.CloudDirectory,
		aws.CloudFormation,
		aws.CloudFront,
		aws.CloudSearch,
		aws.CloudTrail,
		aws.CodeArtifact,
		aws.CodeBuild,
		aws.CodeCommit,
		aws.CodeDeploy,
		aws.CognitoIDP,
		aws.CognitoIdentity,
		aws.CognitoSync,
		aws.Comprehend,
		aws.ComputeOptimizer,
		aws.ConfigService,
		aws.DMS,
		aws.DS,
		aws.DataBrew,
		aws.DataExchange,
		aws.DeviceFarm,
		aws.DevopsGuru,
		aws.DirectConnect,
		aws.Dynamodb,
		aws.DynamodbStreams,
		aws.EC2,
		aws.ECR,
		aws.ECRPublic,
		aws.ECS,
		aws.EKS,
		aws.ELB,
		aws.ES,
		aws.ElasticBeanStalk,
		aws.ElasticFileSystem,
		aws.Elasticache,
		aws.Email,
		aws.Events,
		aws.FSX,
		aws.Forecase,
		aws.FraudDetector,
		awsEndpoint,
		aws.GameLift,
		aws.Glue,
		aws.Grafana,
		aws.GreenGrass,
		aws.GroundStation,
		aws.GuardDuty,
		aws.IAM,
		aws.IOT,
		aws.IOT1ClickDevices,
		aws.IOT1ClickProjects,
		aws.IOTAnalytics,
		aws.IOTData,
		aws.IOTDeviceAdvisor,
		aws.IOTEvents,
		aws.IOTEventsData,
		aws.IOTFleetHub,
		aws.IOTFleetWise,
		aws.IOTJobsData,
		aws.IOTRoboRunner,
		aws.IOTThingsGraph,
		aws.IOTWinMaker,
		aws.ImageBuilder,
		aws.Inspector,
		aws.Inspector2,
		aws.IotWireless,
		aws.KMS,
		aws.Kafka,
		aws.KafkaConnect,
		aws.Kinesis,
		aws.KinesisVideo,
		aws.LakeFormation,
		aws.Lambda,
		aws.LicenseManager,
		aws.LightSail,
		aws.Logs,
		aws.MQ,
		aws.Macie,
		aws.Macie2,
		aws.MediaConvert,
		aws.MediaLive,
		aws.MediaStore,
		aws.Mediaconnect,
		aws.MemoryDB,
		aws.MigrationHubStratergy,
		aws.NetworkFirewall,
		aws.Opensearch,
		aws.Organizations,
		aws.Outposts,
		aws.Panorama,
		aws.Personalize,
		aws.Polly,
		aws.Proton,
		aws.RDS,
		aws.Redshift,
		aws.RedshiftData,
		aws.RedshiftServerless,
		aws.Robomaker,
		aws.Route53,
		aws.Route53Domains,
		aws.Route53Resolver,
		aws.S3,
		aws.S3Control,
		aws.S3Outposts,
		aws.SMS,
		aws.SNS,
		aws.SQS,
		aws.SSM,
		aws.STS,
		aws.SageMaker,
		aws.Scheduler,
		aws.SecretsManager,
		aws.SecurityHub,
		aws.SecurityLake,
		aws.ServiceCatalog,
		aws.ServiceQuotas,
		aws.Shield,
		aws.Snowball,
		aws.StorageGateway,
		aws.Transcribe,
		aws.Transfer,
		aws.Translate,
		aws.VoiceID,
		aws.WAF,
		aws.WAFRegional,
		aws.WafV2,
		aws.Wellarchitected,
		aws.Workdocs,
		aws.Workspaces,
		aws.WorkspacesWeb,
		aws.Xray,
	},
}

func getAwsServiceGroups() []string {
	var groups []string
	for k := range AwsServiceGrouping {
		groups = append(groups, k)
	}
	return groups
}

// getRegions if all is specific, returns all regions
func getRegions(regions []string) []string {
	regions = shared.RemoveDuplicates(regions)
	for _, r := range regions {
		if r == "all" {
			return aws_Regions
		}
	}
	return regions
}
