on:
  push:
    branches:
      - master

name: Build DEV

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup go
        uses: actions/setup-go@v2.1.3
        with:
          version: "1.17"

      - uses: actions/cache@v2.1.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build with goreleaser
        uses: goreleaser/goreleaser-action@3.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-announce --rm-dist --snapshot

      - name: Delete DEV release
        uses: actions/github-script@v6
        with:
          script: |
            const {data} = await github.rest.repos.getReleaseByTag({
              owner: 'securisec',
              repo: 'cliam',
              tag: 'DEV'
            });
            
            if (data) {

              try {
                await github.rest.repos.deleteRelease({
                  owner: 'securisec',
                  repo: 'cliam',
                  release_id: data.id
                });
              } catch (e) {
                console.error(e);
              }

            }

      - name: Release DEV
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: DEV
          overwrite: true
          release_name: DEV
          file_glob: true
          file: dist/build/*
