on:
  - push

name: Build *nix
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup go
        uses: actions/setup-go@v2.1.3
        with:
          version: "1.17"

      - uses: actions/cache@v2.1.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build with goreleaser
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-announce --rm-dist --snapshot

      - name: Delete DEV release
        uses: actions/github-script@v6
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: 'securisec',
              repo: 'cliam',
              tag: 'DEV'
            });
            if (release) {
              await github.rest.repos.deleteRelease({
                owner: 'securisec',
                repo: 'cliam',
                release_id: release.id
              });
            }

      - name: Release DEV
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: DEV
          overwrite: true
          release_name: DEV
          file_glob: true
          file: dist/build/*


      - name: Release tagged
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          file: dist/build/*

      - if: failure()
        run: ls -R