on:
  push:
    tags:
      - "*"

name: Build release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup go
        uses: actions/setup-go@v3.2.0
        with:
          version: "1.18"
          cache: true

      - uses: actions/cache@v2.1.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build with goreleaser
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-announce --rm-dist --snapshot

      - name: Release tagged
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          file: dist/build/*

      - if: failure()
        run: ls -R